### ISSUE TITLE
Upgrading fortinet.fortimanager collection from 2.7.0 to 2.8.x breaks playbook

### ISSUE THREAD

**Issue by Superset1986** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#101]
I’m currently using the fortinet.fortimanager collection v2.7.0, and my playbook runs successfully. However, after upgrading to any 2.8.x version, the same playbook that previously worked now fails with an error.

Playbook:

```
- hosts: fortimanager
  connection: httpapi
  gather_facts: false
  collections:
    - fortinet.fortimanager
    - ansible.netcommon
    - ansible.util

  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
    ansible_network_os: fortinet.fortimanager.fortimanager
  
  tasks:
    - name: Retrieve device
      fortinet.fortimanager.fmgr_fact:
        access_token: '{{ fmg_access_token }}'
        facts:
          selector: "dvmdb_device"
          params:
            adom: "root"
            device: "my-Fortigate"
          option:
            - "get meta"
```
Error Message (in 2.8.x):

`ansible.module_utils.connection.ConnectionError: Error -11 -- the Session ID was likely malformed somehow. Exiting`

Has anything changed in v2.8.x that could cause this issue?
