### ISSUE TITLE
fortinet.fortimanager.fmgr_securityconsole_install_package stucks when preview with policy package defined into subfolders

### ISSUE THREAD

**Issue by apellini** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#102]
We are trying to use following task on a policy package create on subfolder into the ADOM:

```
- name: Install for policy package [preview mode] 
  fortinet.fortimanager.fmgr_securityconsole_install_package:
    workspace_locking_adom: ADOM1
    workspace_locking_timeout: 120
    securityconsole_install_package:
      adom: ADOM1
      pkg: SUB/SUB2/PPKG
      flags:
        - preview
  register: r
  until: r.rc == 0
  retries: 5
  delay: 60
```

But Fortimanager start a Install Preview and never end its operations and task goes in fatal status.

There is another mode to use packages in case are in a subfolder?

**Comment by MaxxLiu22** [comment]
Hi @apellini ,

Thank you for your question. You may need to define the ``scope`` parameter to specify the target device for the package installation. Please note that the device should already be associated with the package—you can verify this by right-clicking the package and selecting the Install Wizard, as shown in the attached screenshot.

There is a playbook available that first generates a preview of the changes and then commits those changes to the device.
If you'd prefer to only view the preview without applying the changes, you can comment out the commit task and use the cancel task at the end. Let me know if that doesn't solve your question.

![Image](https://github.com/user-attachments/assets/393aa60e-51e5-4be2-8c6b-2b50e14d38c4)

```
- hosts: fortimanager01
  collections:
    - fortinet.fortimanager
  connection: httpapi
  gather_facts: false
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
    adom: root
    ppkg: sub/sub2/new_pkg
    device: FortiGate-VM64-KVM
  tasks:
    - name: Install for policy package [preview mode] {{ ppkg }}
      fortinet.fortimanager.fmgr_securityconsole_install_package:
        securityconsole_install_package:
          adom: "{{ adom }}"
          flags:
            - preview
          pkg: "{{ ppkg }}"
          scope:
            - name: "{{ device }}"
              vdom: "root"
      register: r

    - name: Poll the task waiting for preview install task done
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "task_task"
          params:
            task: "{{ r.meta.response_data.task }}"
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5

    - name: Trigger the preview report generation for policy package {{ ppkg }}
      fortinet.fortimanager.fmgr_securityconsole_install_preview:
        securityconsole_install_preview:
          adom: "{{ adom }}"
          scope:
            - name: "{{ device }}"
              vdom: "root"
      register: r

    - name: Poll the task waiting for preview generation task done
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "task_task"
          params:
            task: "{{ r.meta.response_data.task }}"
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5

    - name: Get the preview report for policy package {{ ppkg }}
      fortinet.fortimanager.fmgr_securityconsole_preview_result:
        securityconsole_preview_result:
          adom: "{{ adom }}"
          scope:
            - name: "{{ device }}"
              vdom: "root"
      register: r
    - name: Show preview result
      ansible.builtin.debug:
        msg: "{{ r }}"

    - name: Install policies to device from preview cache.
      fortinet.fortimanager.fmgr_securityconsole_package_commit:
        securityconsole_package_commit:
          adom: "{{ adom }}"
          scope:
            - name: "{{ device }}"
              vdom: "root"
      register: r
    - name: Poll the task
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "task_task"
          params:
            task: "{{ r.meta.response_data.task }}"
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5

    # - name: Cancel install task for policy package {{ ppkg }}
    #   fortinet.fortimanager.fmgr_securityconsole_package_cancel_install:
    #     securityconsole_package_cancel_install:
    #       adom: "{{ adom }}"
```
you will get result like this:
```
root@liang:~/ansible/fmg/github102# ansible-playbook -i host preview_commit_change.yml 

PLAY [fortimanager01] **************************************************************************************************************************************************************************

TASK [Install for policy package [preview mode] sub/sub2/new_pkg] ******************************************************************************************************************************
changed: [fortimanager01]

TASK [Poll the task waiting for preview install task done] *************************************************************************************************************************************
FAILED - RETRYING: [fortimanager01]: Poll the task waiting for preview install task done (30 retries left).
ok: [fortimanager01]

TASK [Trigger the preview report generation for policy package sub/sub2/new_pkg] ***************************************************************************************************************
changed: [fortimanager01]

TASK [Poll the task waiting for preview generation task done] **********************************************************************************************************************************
FAILED - RETRYING: [fortimanager01]: Poll the task waiting for preview generation task done (30 retries left).
FAILED - RETRYING: [fortimanager01]: Poll the task waiting for preview generation task done (29 retries left).
ok: [fortimanager01]

TASK [Get the preview report for policy package sub/sub2/new_pkg] ******************************************************************************************************************************
changed: [fortimanager01]

TASK [Show preview result] *********************************************************************************************************************************************************************
ok: [fortimanager01] => {
    "msg": {
        "changed": true,
        "failed": false,
        "meta": {
            "request_url": "/securityconsole/preview/result",
            "response_code": 0,
            "response_data": {
                "message": "[{ \"name\": \"FortiGate-VM64-KVM\", \"oid\": 178, \"result\": \"=== Preview result ===\\nconfig vdom\\n    edit root\\n        config firewall policy\\n            edit 1\\n                set name \\\"fmg_test234\\\"\\n            next\\n        end\\n    end\\n\"}]"
            },
            "response_message": "OK",
            "system_information": {
                "Admin Domain Configuration": "Disabled",
                "BIOS version": "04000002",
                "Branch Point": "2553",
                "Build": "2553",
                "Current Time": "Thu Apr 17 11:05:04 PDT 2025",
                "Daylight Time Saving": "Yes",
                "FIPS Mode": "Disabled",
                "HA Mode": "Stand Alone",
                "Hostname": "FGT-VM-106",
                "License Status": "Valid",
                "Major": 7,
                "Max Number of Admin Domains": 10000,
                "Max Number of Device Groups": 10000,
                "Minor": 4,
                "Offline Mode": "Disabled",
                "Patch": 5,
                "Platform Full Name": "FortiManager-VM64-KVM",
                "Platform Type": "FMG-VM64-KVM",
                "Release Version Information": " (GA.M)",
                "Serial Number": "FMG-VMTM24012097",
                "TZ": "US/Pacific",
                "Time Zone": "(GMT-8:00) Pacific Time (US & Canada).",
                "Version": "v7.4.5-build2553 241016 (GA.M)",
                "x86-64 Applications": "Yes"
            }
        },
        "rc": 0
    }
}

TASK [Install policies to device from preview cache.] ******************************************************************************************************************************************
changed: [fortimanager01]

TASK [Poll the task] ***************************************************************************************************************************************************************************
FAILED - RETRYING: [fortimanager01]: Poll the task (30 retries left).
FAILED - RETRYING: [fortimanager01]: Poll the task (29 retries left).
FAILED - RETRYING: [fortimanager01]: Poll the task (28 retries left).
FAILED - RETRYING: [fortimanager01]: Poll the task (27 retries left).
FAILED - RETRYING: [fortimanager01]: Poll the task (26 retries left).
ok: [fortimanager01]

PLAY RECAP *************************************************************************************************************************************************************************************
fortimanager01             : ok=8    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```

Thanks,
Maxx

**Comment by apellini** [comment]
The issue is that the policy package is into a subfolder (ex FOLD/SUB/<package name>), infact if we use a policy package that is in root folder task works correctly.

**Comment by MaxxLiu22** [comment]
Hi @apellini ,

May I kindly ask what your subfolder structure looks like, and which FMG version you are using? It works well on my FMG version 7.6.1 with workspace enabled.

![Image](https://github.com/user-attachments/assets/2068f8dd-b7c1-4223-94e6-2cc4e0b29c23)

![Image](https://github.com/user-attachments/assets/0eae86a0-9a0a-4168-9ee2-6a4882b5fc75)

**Comment by apellini** [comment]
Hi do you have any news on it?

**Comment by dux-fortinet** [comment]
I tried to reproduce this error. Yet the script works well in my environment  (FortiManager 6.4.10).

Could you please add "enable_log: true" in your playbook to enable logging data? And the log will be appended to the file `/tmp/fortimanager.ansible.log`

[script]
```
- name: Github102
  hosts: fortimanagers
  gather_facts: false
  vars:
    adom_name: "root"
  tasks:
    - name: Install for policy package [preview mode]
      fortinet.fortimanager.fmgr_securityconsole_install_package:
        workspace_locking_adom: ADOM1
        workspace_locking_timeout: 120
        enable_log: true                   # <---- here
        securityconsole_install_package:
          adom: ADOM1
          flags:
            - preview
          pkg: SUB/SUB2/PPKG
      register: r
      until: r.rc == 0
      retries: 5
      delay: 60
```

You should find the log like
[example log]
```
2025-04-30 20:44:17.328421: request: {"method": "exec", "params": [{"url": "/securityconsole/install/package", "data": {"adom": "ADOM1", "flags": ["preview"], "pkg": "SUB/SUB2/PPKG"}}], "session": "<session>", "id": 9, "verbose": 1}
2025-04-30 20:44:17.525281: response: {
   "id": 9,
   "result": [
      {
         "data": {
            "task": 20
         },
         "status": {
            "code": 0,
            "message": "OK"
         },
         "url": "/securityconsole/install/package"
      }
   ]
}
```

Please provide the response log (mask necessary information if you need) to us so we can figure out what happened.

Thanks,
Xinwei
