### ISSUE TITLE
Never ending task with fmgr_securityconsole_install_preview

### ISSUE THREAD

**Issue by Lextum** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#15]
If i create a preview with a wrong device, the task on the FortiManager never stops and we need to delete it by hand. (Maybe there is an timeout, but it ran for over 8 minutes in one of my tests). 

Shouldn't the module check, if the device even exists? Or is there a way, the ask the FortiManager, if the device exist before we execute the fmgr_securityconsole_install_preview command?

I am trying to get a preview of the policy change and output the the change to the console. With change i mean something like new firewall rule. The same you would get with the **Policy Package Diff** in the web interface.

I found 3 modules, that looked promising.
fmgr_securityconsole_reinstall_package --> create a preview with the right flag, but only outputs the task id.
fmgr_securityconsole_install_preview --> does something
fmgr_securityconsole_preview_result --> only work if fmgr_securityconsole_install_preview finished before, but gives me no output either.

Do i miss something?

**Comment by chillancezen** [comment]
hi @Lextum, 
> Shouldn't the module check, if the device even exists? Or is there a way, the ask the FortiManager, if the device exist before we execute the fmgr_securityconsole_install_preview command?

Ansible is not aware of a device's presence,  nor any other API consumers, we are expected to do check beforehand.
here is one example:
```
$cat query_device.yml
- hosts: fortimanager01
  connection: httpapi
  collections:
  - fortinet.fortimanager
  vars:
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
   target_device: 'FGVM02TM20012347'
  gather_facts: True
  tasks:
   - name: Query The Device to determine the presence.
           # if the device is present, the task succeeds, otherwise, the task fails
           # to handle errors, you may also refer to:
           # https://ansible-galaxy-fortimanager-docs.readthedocs.io/en/latest/errors.html
     fmgr_fact:
        facts:
          selector: 'dvmdb_device'
          params:
            adom: 'root'
            device: '{{ target_device }}'
```

**Comment by chillancezen** [comment]
> Do i miss something?

In FortiManager, few API/module return a task, the task may persist for several minutes before the result is returned. In this case, API consumers/Ansible must poll and wait themselves(just think about FortuiManager Web UI, adding a device/executing a script may also last for several minutes).

here is an example of waiting and polling FortiManager tasks:
```
#source  https://raw.githubusercontent.com/fortinet-ansible-dev/fortimanager-playbook-example/2.0.0/output/commit_config_to_device.yml
#docs: https://ansible-galaxy-fortimanager-docs.readthedocs.io/en/latest/example.html
- name: Commit config to real device
  hosts: fortimanager01
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
    device_adom: 'root'
    script_name: 'FooScript'
    device_name: 'CustomHostName'
    device_vdom: 'root'
  tasks:
    - name: invoke the task
      fmgr_securityconsole_install_device:
        securityconsole_install_device:
            adom: '{{ device_adom }}'
            scope:
             - name: '{{ device_name }}'
               vdom: '{{ device_vdom }}'
      register: installing_task
    - name: Inspect the Task Status
      fmgr_fact:
        facts:
            selector: 'task_task'
            params:
                task: '{{installing_task.meta.response_data.task}}'
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 3
      failed_when: taskinfo.meta.response_data.state == 'error'
```
 thanks,
Link
