### ISSUE TITLE
Documentation Request: Add FortiAnalyzer to FortiManager

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#19]
It would be useful if you've got something similar to this page: https://raw.githubusercontent.com/fortinet-ansible-dev/fortimanager-playbook-example/2.0.0/output/fmgr_dvm_cmd_add_device.yml

I've tried the following, but I'm getting error -24 when

```
    - name: Add FortiAnalyzer devices to FortiManager
      delegate_to: FortiManager
      fmgr_dvm_cmd_add_device:
        bypass_validation: False
        dvm_cmd_add_device:
          adom: root
          device:
            adm_pass: "{{ ansible_password }}"
            adm_usr: "{{ ansible_user }}"
            ip: "{{ ansible_host }}"
            mgmt_mode: faz
            name: "{{ inventory_hostname }}"
          flags:
            - none
            - create_task
            - nonblocking
            - log_dev
      register: task

    - name: Inspect the Task Status
      fmgr_fact:
        facts:
          selector: "task_task"
          params:
            task: "{{ task.meta.response_data.task }}"
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 3
      failed_when: taskinfo.meta.response_data.state == 'error'
```
