### ISSUE TITLE
fmgr_dvmdb_script_execute error invalid value

### ISSUE THREAD

**Issue by glennake** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#21]
When I use the fmgr_dvmdb_script_execute module with the bypass_validation setting specified, the task on FortiManager fails with an "invalid value" error.

Not working:

    - name: "RUN_SCRIPT"
      **bypass_validation: False**
      fmgr_dvmdb_script_execute:
        adom: "root"
        dvmdb_script_execute:
          adom: "root"
          script: "script1"
          scope:
            - name: "TEST-DEVICE-01"
              vdom: "root"

Working:

    - name: "RUN_SCRIPT"
      fmgr_dvmdb_script_execute:
        adom: "root"
        dvmdb_script_execute:
          adom: "root"
          script: "script1"
          scope:
            - name: "TEST-DEVICE-01"
              vdom: "root"

This happens every time and if I remove the bypass_validation setting it works fine.

Software versions used:
Python 3.7.4
Ansible 3.2.0
ansible-playbook 2.10.7
fortinet.fortimanager collection 2.0.1
FortiManager 6.4.5 build 2288

**Comment by chillancezen** [comment]
hi @glennake ,

`bypass_validation` is not the top-level parameter, it's an FMG specific parameter which should be under `fmgr_dvmdb_script_execute `. 


```
- name: "RUN_SCRIPT"
  fmgr_dvmdb_script_execute:
     bypass_validation: False**
    adom: "root"
    dvmdb_script_execute:
      adom: "root"
      script: "script1"
      scope:
        - name: "TEST-DEVICE-01"
          vdom: "root"
```

if the issue persist, could you please paste the full log output?

thanks.
