### ISSUE TITLE
API call /dvmdb/_meta_fields/device do not accept string for length parameter

### ISSUE THREAD

**Issue by nherreyre** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#22]
Hi,

Problem of cast when using fmgr_generic + url /dvmdb/_meta_fields/device => length parameter do not accept "string" value, with prevent using loop/with_item because jinga return a string (even if we cast {{ item.xxx | int }}

the code: 

```
- name: CREATE DEVICE META FIELDS
  fmgr_generic:
    method: add
    params: [
      {
        url: "/dvmdb/_meta_fields/device",
        data: [ {
          importance: "{{ item.importance }}",
          name: "{{ item.name }}",
          **length: "{{ item.length | int }}",   <--- here is the probem**
          status: "enable",
        }
        ],
      },
    ]

  with_items:
   - name: "college_rne"
     importance: "required"
     length: "20" 
```

```
 failed: [fmg] (item={'name': 'college_rne', 'importance': 'required', 'length': '20'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "json": null,
            "method": "add",
            "params": [
                {
                    "data": [
                        {
                            "importance": "required",
                            **"length": "20",               <-- length is always a String with this kind of usage with Loop/Vars.**
                            "name": "college_rne",
                            "status": "enable"
                        }
                    ],
                    "url": "/dvmdb/_meta_fields/device"
                }
            ],
            "rc_failed": null,
            "rc_succeeded": null,
            "workspace_locking_adom": null,
            "workspace_locking_timeout": 300
        }
    },
    "item": {
        "importance": "required",
        "length": "20",
        "name": "college_rne"
    },
    "meta": {
        "request_url": "/dvmdb/_meta_fields/device",
        "response_code": -8,
        "response_data": [],
        "response_message": "Invalid parameter"
    },
    "rc": -8
}
```

This is working if using hard coded integer:

  fmgr_generic:
    method: add
    params: [
      {
        url: "/dvmdb/_meta_fields/device",
        data: [ {
          importance: "{{ item.importance }}",
          name: "{{ item.name }}",
          **length: 20,        <----** 
          status: "enable",
        }
        ],
      },
    ]
```

changed: [fmg] => (item={'name': 'college_rne', 'importance': 'required', 'length': '20'}) => {
    "ansible_loop_var": "item",
    "changed": true,
    "invocation": {
        "module_args": {
            "json": null,
            "method": "add",
            "params": [
                {
                    "data": [
                        {
                            "importance": "required",
                            **"length": 20,    <--- direct Integer**
                            "name": "college_rne",
                            "status": "enable"
                        }
                    ],
                    "url": "/dvmdb/_meta_fields/device"
                }
            ],
            "rc_failed": null,
            "rc_succeeded": null,
            "workspace_locking_adom": null,
            "workspace_locking_timeout": 300
        }
    },
    "item": {
        "importance": "required",
        "length": "20",
        "name": "college_rne"
    },
    "meta": {
        "request_url": "/dvmdb/_meta_fields/device",
        "response_code": 0,
        "response_data": [],
        "response_message": "OK"
    },
    "rc": 0

```

**Comment by chillancezen** [comment]
hi @nherreyre ，

the conversion is interpreted by Ansible, and we don't have a viable fix for it. 

however we can work it around by pre-build the parameter body like what is done below:
```
- hosts: fortimanager01
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
   adom: "root"
   ansible_httpapi_use_ssl: True
   ansible_httpapi_validate_certs: False
   ansible_httpapi_port: 443
   ansible_network_os: fortinet.fortimanager.fortimanager
  tasks:

    - name: construct the parameter body array.
      set_fact:
        body_array: "{{ body_array|default([]) + [{ 'length': item.length | int, 'name': item.name, 'importance': item.importance, 'status': 'enable'}] }}"

      with_items:
        - name: "college_rne"
          importance: "required"
          length: "20"
        - name: "college_rnf"
          importance: "required"
          length: "25"

    - name: CREATE DEVICE META FIELDS
      fmgr_generic:
        method: add
        params: [
         {
             url: "/dvmdb/_meta_fields/device",
             data: [
                "{{ item }}"
             ]
         }
        ]
      with_items: "{{ body_array }}"
```

could you please have a try? and let us know if the issue persists.
