### ISSUE TITLE
fmgr_user_group: member should be of type list not str

### ISSUE THREAD

**Issue by jeeden** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#27]
Without a list, it is not posssible to add more than one member to a group

**Comment by jpforcioli** [comment]
Hi,

It's a well known issue.
To workaround it, please add turn on `bypass_validation` as shown below:

```
---
- hosts: fmg4
  connection: httpapi
  collections:
    - fortinet.fortimanager
  gather_facts: false
  vars:
  tasks:
  - name: Add members to user group
    fmgr_user_group:
        bypass_validation: true
        adom: demo_001
        state: present
        user_group:
           name: user_group_01
           member:
             - user01
             - user02
  
```
