### ISSUE TITLE
fmgr_devprof_system_dns does not work under FortiManager 6.4.6 anymore

### ISSUE THREAD

**Issue by ElPajaroBobo** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#32]
Hi,

we are having trouble configuring our dns servers via the provisioning template feature in ansible. 
In previous versions this worked fine, since we upgraded to v6.4.6 we get errors that this module is not supported anymore, but we can't find any deprectation documented or any alternatives. Are there plans to bring this feature back?

```json
[WARNING]: Ansible has detected version mismatch between FortiManager and your playbook, see more details by appending option -vvv
changed: [<hostname>] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "adom": "<myadom>",
            "bypass_validation": false,
            "devprof": "<mydevprof>",
            "devprof_system_dns": {
                "cache-notfound-responses": null,
                "dns-cache-limit": null,
                "dns-cache-ttl": null,
                "dns-over-tls": null,
                "domain": "mydomain.local",
                "interface": null,
                "interface-select-method": null,
                "ip6-primary": "<ipv6-dns-server>",
                "ip6-secondary": "<ipv6-dns-server>",
                "primary": "<ipv4-dns-server>",
                "retry": null,
                "secondary": "<ipv4-dns-server>",
                "server-hostname": null,
                "ssl-certificate": null,
                "timeout": null
            },
            "enable_log": false,
            "proposed_method": "set",
            "rc_failed": null,
            "rc_succeeded": null,
            "workspace_locking_adom": "<myadom>",
            "workspace_locking_timeout": 300
        }
    },
    "meta": {
        "request_url": "/pm/config/adom/<myadom>/devprof/<mydevprof>/system/dns",
        "response_code": 0,
        "response_data": [],
        "response_message": "OK",
        "system_information": {
            "Admin Domain Configuration": "Enabled",
            "BIOS version": "04000002",
            "Branch Point": "2363",
            "Build": "2363",
            "Current Time": "Mon Sep 13 12:19:00 CEST 2021",
            "Daylight Time Saving": "Yes",
            "FIPS Mode": "Disabled",
            "HA Mode": "Stand Alone",
            "Hostname": "hostname",
            "License Status": "Valid",
            "Major": 6,
            "Max Number of Admin Domains": 10,
            "Max Number of Device Groups": 10,
            "Minor": 4,
            "Offline Mode": "Disabled",
            "Patch": 6,
            "Platform Full Name": "FortiManager-VM64",
            "Platform Type": "FMG-VM64",
            "Release Version Information": " (GA)",
            "Serial Number": "FMG-**********",
            "Time Zone": "(GMT+1:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna.",
            "Version": "v6.4.6-build2363 210531 (GA)",
            "x86-64 Applications": "Yes"
        }
    },
    "rc": 0,
    "version_check_warning": {
        "mismatches": [
            "param: devprof_system_dns-->domain not supported since v6.4.0",
            "param: devprof_system_dns-->ip6-primary not supported since v6.4.0",
            "param: devprof_system_dns-->ip6-secondary not supported since v6.4.0",
            "param: devprof_system_dns-->primary not supported since v6.4.0",
            "param: devprof_system_dns-->secondary not supported since v6.4.0"
        ],
        "system_version": "v6.4.6"
    }
}
```

Cheers Sascha

**Comment by albertogd** [comment]
I've the same issue in FortiManager 7.4.2. Is there any alternative for FortiManager 7.x?

The code:

```
- name: Configure DNS
  fmgr_devprof_system_dns:
    bypass_validation: False
    access_token: "{{fortitoken}}"
    workspace_locking_adom: "{{item.adomname}}"
    workspace_locking_timeout: 300
    rc_succeeded: [-2]
    adom: "{{item.adomname}}"
    devprof: "{{item.systemtemplatename}}"
    devprof_system_dns:
      primary: "{{item.dns.primary}}"
      secondary: "{{item.dns.secondary}}"
      interface-select-method: "{{item.dns.intselectmethod}}"
  loop: "{{conffile.system}}"
```

The error:

```
    "version_check_warning": {
        "mismatches": [
            "param: devprof_system_dns-->primary not supported since v6.4.1",
            "param: devprof_system_dns-->secondary not supported since v6.4.1",
            "param: devprof_system_dns-->interface-select-method not supported since v6.4.1"
        ],
        "system_version": "v7.4.2"
    },
```
