### ISSUE TITLE
Issue when creating multiple address objects (loop)

### ISSUE THREAD

**Issue by mpsikorski** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#34]
Hi,

again we tried to use the new Ansible (ansible-2.9.23-1.el7.noarch centos7) modules for creating address objects in Fortimanager v6.2.8-build1435 and after you fixed something in 2.1.4 it works for single objects.
If we try to create multiple objects with a loop the ADOM doesn't get unlocked and saved after the objects are created.

This issue exists at least with the modules:
- fmgr_firewall_address
- fmgr_firewall_address6

Example:
```
---
- name: Address and Address Group Creation
  hosts: FORTINET_FORTIMANAGER
  connection: httpapi
  collections:
    - fortinet.fortimanager
  gather_facts: no
  vars:
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443

  vars_prompt:
  - name: "ansible_user"
    prompt: "Username"
    private: no
    default: "{{ lookup('env', 'USER') }}"
  - name: "ansible_password"
    prompt: "Password"
  - name: "adom"
    prompt: "Adom"
    private: no

  tasks:
    # Addresses
    - name: Create any ipv4 net/addr obj
      fmgr_firewall_address:
        workspace_locking_adom: "Unitymedia"
        workspace_locking_timeout: 300
        adom: "Unitymedia"
        state: "present"
        enable_log: yes
        bypass_validation: False
        proposed_method: "add"
        firewall_address:
          allow-routing: disable
          comment: ""
          type: "ipmask"
          subnet: "{{ item.net }}"
          name: "{{ item.name }}"
          visibility: enable
      loop:
      - name: "TestHost"
        net: "12.12.12.12/32"
      - name: "TestNet"
        net: "12.12.12.0/24"
```
