### ISSUE TITLE
Again issues with creating addresses (fmgr_firewall_address)

### ISSUE THREAD

**Issue by mpsikorski** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#39]
Hi,
we updated our FortiManager to version 6.4.7. 
After trying again the module fmgr_firewall_address with test data the adom gets locked, neither the commit nor the unlock happens but the response message is changed=true.
I also tried to add a task with module fmgr_pm_config_workspace_unlock - after that the unlock happens but still no commit (so the address objects doesn't get created).

Would you please investigate? I tested with collection v.2.1,5.

```
---
- name: Address and Address Group Creation
  hosts: FORTINET_FORTIMANAGER
  connection: httpapi
  collections:
  - fortinet.fortimanager
  gather_facts: no
  vars:
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
    adom: "TEST_ADOM"
    package: "Testpackage"
  vars_prompt:
  - name: "ansible_user"
    prompt: "Username"
    private: no
    default: "{{ lookup('env', 'USER') }}"
  - name: "ansible_password"
    prompt: "Password"

  tasks:
    - name: new block
      block:
        - name: Create any ipv4 net
          fmgr_firewall_address:
            workspace_locking_adom: "{{ adom }}"
            workspace_locking_timeout: 30
            adom: "{{ adom }}"
            state: "present"
            enable_log: yes
            bypass_validation: False
            proposed_method: "add"
            firewall_address:
              allow-routing: disable
              comment: "TESTv4"
              type: "ipmask"
              subnet: "4.3.3.0/24"
              name: "myTestIP"
          register: message
        - name: Unlock an ADOM.
          fmgr_pm_config_workspace_unlock:
            bypass_validation: False
            workspace_locking_adom: "{{ adom }}"
            workspace_locking_timeout: 300
            adom: "{{ adom }}"
```
