### ISSUE TITLE
fmgr_firewall_addrgrp. - can't update with more than one object

### ISSUE THREAD

**Issue by williamnie2088** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#4]
Hi there,

i noticed there is a problem with updating the object-group with more than one object with this module - please let us know if there is any plan for fix on this:

++++++++++++
playbook:
++++++++++++

- name: install object and object-group to Fortimanager device 
  hosts: FortiManager
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars_files:
    - vars/add_address_ipv4_group.yml
  tasks:
    - name: Create the firewall address object-group
      fmgr_firewall_addrgrp:
        method: "set"
        url_params:
            adom: "{{ item.adom }}"
        params:
          - data:
              - name: "{{ item.name }}"
                comment: "address object created via generic ansible module"
                visibility: "enable"
                member: "{{ item.group }}"
                color: 7
      loop: "{{ group_info }}"
...

++++++++++++
vars:
++++++++++++
---
group_info:
- adom: global
  name: test_netgroup_global_vpn_x_x_x_x
  group: 
    netgroup_corp_den01_adminvpn_x.x.x.x,
    netgroup_corp_den01_adminvpn_x.x.x.x,
    netgroup_corp_sec01_adminvpn_x.x.x.x

getting following skip message:

        "status": {
            "code": -10131,
            "message": "datasrc invalid. object: firewall addrgrp.test_netgroup_global_vpn_172_x_x_x:member. detail:  netgroup_corp_den01_adminvpn_x, netgroup_corp_den01_adminvpn_x, netgroup_corp_sec01_adminvpn_x. solution: datasrc invalid"
        },

in method i have tried: set, update and add -- no difference

thanks

**Comment by chillancezen** [comment]
thank @williamnie2088 for the issue.

here is the workaround for your issue, please make sure they are pre-created:
```
---
group_info:
- adom: global
  name: test_netgroup_global_vpn_x_x_x_x
  group: 
     - netgroup_corp_den01_adminvpn_x.x.x.x
     - netgroup_corp_den01_adminvpn_x.x.x.x
     - netgroup_corp_sec01_adminvpn_x.x.x.x
```

then add a line `loose_validation: True` in the playbook.

```
- name: install object and object-group to Fortimanager device 
  hosts: FortiManager
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars_files:
    - vars/add_address_ipv4_group.yml
  tasks:
    - name: Create the firewall address object-group
      fmgr_firewall_addrgrp:
        loose_validation: True
        method: "set"
        url_params:
            adom: "{{ item.adom }}"
        params:
          - data:
              - name: "{{ item.name }}"
                comment: "address object created via generic ansible module"
                visibility: "enable"
                member: "{{ item.group }}"
                color: 7
      loop: "{{ group_info }}"
```

thanks,
Link.
