### ISSUE TITLE
'Object does not exist' error when calling firewall_address with '/' in the name

### ISSUE THREAD

**Issue by kaon1** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#42]
I'm getting an error when calling `fortinet.fortimanager.fmgr_fact` firewall address if the name has a '/' character

The object does exist, I am able to pull it up directly on the fortimanager web gui and the API (via Postman)

I'm running fortimanager `v6.2.8`
galaxy version `fortinet.fortimanager:2.1.5`
ansible version `ansible-playbook 2.9.5`
python version `python version = 3.6.8`

```
TASK [Get google object] ***************************************************************************************************************************************************************************************************************************************
fatal: [fortimanager01: FAILED! => {"changed": false, "meta": {"request_url": "/pm/config/adom/6_2_ADOM/obj/firewall/address/Google-35.192.0.0/12", "response_code": -3, "response_data": [], "response_message": "Object does not exist",
```

```
    - name: Get google object
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: 'firewall_address'
          params:
            adom: '6_2_ADOM'
            address: "Google-35.192.0.0/12"
      register: google_object
```

**Comment by lix-fortinet** [comment]
Hi @kaon1,

Thank you for raising this issue. Team is working on this issue, and we will fix it in the next release. We will get back to you once it's resolved. Before that, you could add `\\` before `/`. For instance: 
```
    - name: Get google object
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: 'firewall_address'
          params:
            adom: '6_2_ADOM'
            address: "Google-35.192.0.0\\/12"
      register: google_object
```

Thanks,
Xing
