### ISSUE TITLE
Can't create VIP with fmgr_firewall_vip_obj

### ISSUE THREAD

**Issue by rrobles12** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#6]
Hello,

I can't seem to create a VIP with the module fmgr_firewall_vip_obj. Here is my ansible version:

```
  ansible 2.10.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/rrobles/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rrobles/.local/lib/python3.6/site-packages/ansible
  executable location = /home/rrobles/.local/bin/ansible
  python version = 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
```

Here is the collection version:

```
# /home/rrobles/.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
ansible.netcommon     1.2.1
fortinet.fortimanager 1.0.5
fortinet.fortios      1.0.13
```

The playbook executed looks like this:

```
---
- name: CONFIGURE VIP OBJECTS
  fmgr_firewall_vip_obj:
    loose_validation: "True"
    method: "set"
    url_params:
      adom: "{{ adom }}"
      vip: "VIP1"
    params:
       -
          data:
            -
                name: "VIP1"
                extintf: "any"
                extip: "9.9.9.9"
                mappedip:
                  - "192.168.1.1"
```

I keep getting the following:

```
'fatal: [fortimgrvm-lab]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "loose_validation": true,
            "method": "set",
            "params": [
                {
                    "data": [
                        {
                            "extintf": "any",
                            "extip": "9.9.9.9",
                            "mappedip": [
                                {
                                    "192.168.1.1"
                                }
                            ],
                            "name": "VIP1"
                        }
                    ]
                }
            ],
            "url_params": {
                "adom": "NONPROD",
                "vip": "VIP1"
            },
            "workspace_locking_adom": null,
            "workspace_locking_timeout": 300
        }
    },
    "meta": {
        "status": {
            "code": -10,
            "message": "The data is invalid for selected url"
        },
        "url": "/pm/config/adom/NONPROD/obj/firewall/vip/VIP1"
    },
    "unreachable": false
}
```

I've tried with and without the url_params vip but the result is the same. Any help would be appreciated, I must be missing something simple. It would also help if like the old ansible documentation, it would clearly flag required parameters for each module. The galaxy format is nice, but less useful as it doesn't clearly show what is the bare minimum required for a module to run successfully.

Thanks
