### ISSUE TITLE
Can't execute Script, adom parameter is missing from the API call

### ISSUE THREAD

**Issue by webtroter** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#63]
Hi,

On FortiManager 6.4, using the collection @2.0.4, I cannot execute script from Ansible.

Testing with the FortiManager Postman Collection, I was able to find where the bug is.

Here is the API Request made by the Ansible Collection : 
```
{
    "method": "exec",
    "params": [
        {
            "url": "/dvmdb/adom/MYADOM/script/execute",
            "data": {
                "script": "LocalUserForAPI",
                "scope": [
                    {
                        "name": "Fortigate1"
                    },
                    {
                        "vdom": "root"
                    }
                ]
            }
        }
    ],
    "session": "redacted",
    "id": 12,
    "verbose": 1
}
```

FMG API replies with
```
{ "id": 12, "result": [ { "status": { "code": -10, "message": "The data is invalid for selected url" }, "url": "\/dvmdb\/adom\/MYADOM\/script\/execute" } ] }
```

When I test with Postman, I have no problem because the "adom" field is present in the "data" object.

```
{
    "method": "exec",
    "params": [
        {
            "data": {
                "adom": "MYADOM",
                "scope" : [
                    {
                        "name": "Fortigate1",
                        "vdom": "root"
                    }
                ],
                "script": "TestScript"
            },
            "url": "/dvmdb/adom/MYADOM/script/execute"
        }
    ],
    "session": "{{fmg-session}}",
    "verbose": 1,
    "id": 1
}
```

Please let me know if you need additional information to fix this bug.

Thank you,

Alexis

**Comment by webtroter** [comment]
> What playbook code are you using?

Ahh, yes, good point. The ADOM was in fact missing from my playbook (it was commented out).

Even with the ADOM declaration, I still get the "Invalid Parameter" error.

I can Install the Script, but I cannot execute them.

Playbook:
```yaml
- name: Setup Local API Users
  hosts: FortiManager
  connection: httpapi
  strategy: debug
  gather_facts: false
  vars:
    ansible_user: "admin@example.org"
    fortimanager_adom: "MYADOM"
    script_name: "LocalUserForAPI"
  tasks:
    - name: Install Script
      fortinet.fortimanager.fmgr_dvmdb_script:
        dvmdb_script:
          content: "{{ lookup('file', 'localapiuser_script.fmg') }}"
          name: "{{ script_name }}"
          desc: Script Added via Ansible
          type: cli
        adom: "{{ fortimanager_adom }}"
        state: present
        # workspace_locking_adom: "{{ fortimanager_adom }}"
        # workspace_locking_timeout: 180
    - name: Run the script
      fortinet.fortimanager.fmgr_dvmdb_script_execute:
        dvmdb_script_execute:
          script: "{{ script_name }}"
          adom: "{{ fortimanager_adom }}"
          scope:
            - name: "FGT01"
            - vdom: "root"
          # package: "device-settings"
        adom: "{{ fortimanager_adom }}"
        enable_log: true
        bypass_validation: true
        # workspace_locking_adom: "{{ fortimanager_adom }}"
        # workspace_locking_timeout: 180
      register: running_task
    - name: Inspect the Task Status
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: 'task_task'
          params:
            task: '{{ running_task.meta.response_data.task }}'
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 3
      failed_when: taskinfo.meta.response_data.state == 'error'
```

I will update the initial post to remove the mention of the bad API call.
