### ISSUE TITLE
Error running fmgr_dvmdb_script_execute

### ISSUE THREAD

**Issue by cpmoves** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#66]
When trying to execute a script and checking the status of the job it's failing. It looks to be sending the oid of the script instead of the name based off what I can see in the Task Monitor comparing a job run from the GUI.  

FMG v6.4.8
fortinet.fortimanager 2.2.0 

    - name: Run the Script
     fmgr_dvmdb_script_execute:
       bypass_validation: False
       adom: '{{ device_adom }}'
       dvmdb_script_execute:
         adom: '{{ device_adom }}'
         script: '{{ script_name }}'
         package: '{{ device_package }}'
         scope:
           -
             name: '{{ device_name }}'
             vdom: '{{ device_vdom }}'
       enable_log: true
     register: running_task

    - name: Inspect the Task Status
     fmgr_fact:
       facts:
         selector: 'task_task'
         params:
           task: '{{running_task.meta.response_data.task}}'
     register: taskinfo
     until: taskinfo.meta.response_data.percent == 100
     retries: 30
     delay: 3
     failed_when: taskinfo.meta.response_data.state == 'error'

-----------------------------------
```
changed: [xxxxx]: FAILED! => {
    "changed": true,
    "invocation": {
        "module_args": {
            "access_token": null,
            "adom": "PreProd-Lab",
            "bypass_validation": false,
            "dvmdb_script_execute": {
                "adom": "PreProd-Lab",
                "package": "PreProd-CDE",
                "scope": null,
                "script": "Ansible_Script"
            },
            "enable_log": true,
            "forticloud_access_token": null,
            "rc_failed": null,
            "rc_succeeded": null,
            "workspace_locking_adom": null,
            "workspace_locking_timeout": 300
        }
    },
    "meta": {
        "request_url": "/dvmdb/adom/PreProd-Lab/script/execute",
        "response_code": 0,
        "response_data": {
            "task": 109201
        },
    "rc": 0
}

fatal: [xxxxx]: FAILED! => {
    "attempts": 2,
    "changed": true,
    "failed_when_result": true,
    "invocation": {
        "module_args": {
            "access_token": null,
            "enable_log": false,
            "facts": {
                "fields": null,
                "filter": null,
                "option": null,
                "params": {
                    "task": "109201"
                },
                "selector": "task_task",
                "sortings": null
            },
            "forticloud_access_token": null,
            "rc_failed": null,
            "rc_succeeded": null,
            "workspace_locking_adom": null,
            "workspace_locking_timeout": 300
        }
    },
    "meta": {
        "request_url": "/task/task/109201",
        "response_code": 0,
        "response_data": {
            "adom": 1081907,
            "end_tm": 1690337466,
            "flags": 0,
            "id": 109201,
            "line": [
                {
                    "detail": "install script 1176374 failed. Reason: Invalid data.",
                    "end_tm": 1690337466,
                    "err": -1,
                    "history": [
                        {
                            "detail": "2023-07-26 12:11:04:start installing script 1176374.",
                            "name": "script 1176374",
                            "percent": 0,
                            "vdom": null
                        },
                        {
                            "detail": "2023-07-26 12:11:06:install script 1176374 failed. Reason: Invalid data.",
                            "name": "script 1176374",
                            "percent": 100,
                            "vdom": null
                        }
                    ],
                    "ip": "",
                    "name": "script 1176374",
                    "oid": 1176374,
                    "percent": 100,
                    "start_tm": 1690337464,
                    "state": "error",
                    "vdom": ""
                }
            ],
            "num_done": 0,
            "num_err": 1,
            "num_lines": 1,
            "num_warn": 0,
            "percent": 100,
            "pid": 0,
            "src": "script installation",
            "start_tm": 1690337464,
            "state": "error",
            "title": "Run Script",
            "tot_percent": 100,
            "user": "api_user"
        },
        "response_message": "OK",
    "rc": 0
}
``` 

![image](https://github.com/fortinet-ansible-dev/ansible-galaxy-fortimanager-collection/assets/108710867/481ba50a-e4d4-4be2-bd52-13298b514253)
    
![image](https://github.com/fortinet-ansible-dev/ansible-galaxy-fortimanager-collection/assets/108710867/1a46a765-579f-4d0a-881f-2fcb0b371193)

**Comment by dux-fortinet** [comment]
Hey cpmoves,

I tried FMG v6.4.8 (managing one FGT V6.4.0) with fortinet.fortimanager 2.2.0. And I didn't encounter the problem you mentioned.

Could you please share the log file so I can figure out what is the cause?

You can get the log file by adding "enable_log: true" in your playbook:
```
- name: Run the Script
  fmgr_dvmdb_script_execute:
    bypass_validation: False
    adom: "{{ device_adom }}"
    dvmdb_script_execute:
      adom: "{{ device_adom }}"
      script: "{{ script_name }}"
      package: "{{ device_package }}"
      scope:
        - name: "{{ device_name }}"
          vdom: "{{ device_vdom }}"
    enable_log: true
  register: running_task

- name: Inspect the Task Status
  fmgr_fact:
    enable_log: true
    facts:
      selector: "task_task"
      params:
        task: "{{running_task.meta.response_data.task}}"
  register: taskinfo
  until: taskinfo.meta.response_data.percent == 100
  retries: 30
  delay: 3
  failed_when: taskinfo.meta.response_data.state == 'error'
```
And the log file will be in '/tmp/fortimanager.ansible.log'. Since the log data will be appended to this file every time you run a playbook, please remember to delete this file (remove history log data) before you run the playbook.

Thanks.
