### ISSUE TITLE
How to create routes in a fortigate over an fortimanager

### ISSUE THREAD

**Issue by patrickpreuss** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#70]
Hello, 

i to create some named routes over to fortimager on an fortigate.
it looks like that this is only possible while directly connecting to the fortigate.

Would be great to have more gateway settings accessible over the fortimanger.

Thanks for the help. 

fortinet.fortimanager         2.2.0
fortinet.fortios              2.3.0

**Comment by dux-fortinet** [comment]
Hi @patrickpreuss,

What kind of route do you want to config? 
It would be great if you could provide some images or example playbooks so we can give you a solution more precisely. 
Currently, you can't config static routes in a FortiGate via FortiManager because FortiManager don't have this API.

Best regards

**Comment by patrickpreuss** [comment]
Hi 

i try to create an named route like:

```
config firewall address
    edit "DESTINATIONS"
        set allow-routing enable
        set subnet 10.0.0.0 255.0.0.0
    next
end
config router static
    edit 1
      set device wan1 
      set gateway 192.168.1.1
      set dstaddr DESTINATIONS
    next 
end

```

Creating the Address(es) is straight forward. 
```
  - name: config for firewall_address
    fmgr_firewall_address:
      bypass_validation: False
      state: present
      adom: "{{ adom }}"
      firewall_address:
        allow-routing: enable
        name: "DESTINATIONS"
        subnet: "10.0.0.0/255.0.0.0"
        type: ipmask
        visibility: enable
        color: 17
    register: info
```
no i would like to have the possibility:
to create the static route on the gateway in the FortiManager

it looks like ` fortios_router_static` is only avail for the direct communication with the gateway.

heaving the fortios_* functions available in the FortiManager would enable to do some more advanced provisioning tasks over the FortiManager.
