### ISSUE TITLE
How to define preferred image version when adding model device to FortiManager? (fmgr_dvm_cmd_add_device)

### ISSUE THREAD

**Issue by cr0cdev** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#71]
Hi!

I'm trying to add a new model device to FMG with preferred firmware version (_image_) so once the device is provisioned by FortiZTP and linked to FMG it will auto upgrade it's version to defined firmware version.
I've used `fmgr_dvm_cmd_add_device` to add the model device, but this does not support defining the image version (`prefer_img_ver`) (_in the API documentation the `dvm/cmd/add/device` does support `prefer_img_ver`_).
```
- name: Add new model device to ADOM "{{ adom_name | lower }}"
  fortinet.fortimanager.fmgr_dvm_cmd_add_device:
    workspace_locking_adom: "{{ adom_name | lower }}"
    dvm_cmd_add_device:
      adom: "{{ adom_name | lower }}"
      device:
        name: "{{ device_name | lower }}"
        os_ver: "{{ device_fos_ver }}"
        os_type: "{{ device_os_type }}"
        mr: "{{ device_fos_mr }}"
        mgmt_mode: "{{ device_fmg_mgmt_mode }}"
        sn: "{{ serial_number | upper }}"
        device action: "{{ device_action }}"
        #prefer_img_ver: "{{ device_fos_img_ver }}"
      flags:
        - "create_task"
        - "nonblocking"
```
Does this mean I should run `fmgr_dvmdb_device` with `prefer_img_ver` and then commit the changes via `fmgr_dvmdb_workspace_commit_dev` after adding the model device?

Thank you!

**Comment by dux-fortinet** [comment]
Hi @cr0cdev,

Thanks for raising this issue.
According to the [API document](https://fndn.fortinet.net/index.php?/fortiapi/5-fortimanager/2699/5/dvm/cmd/add/), `dvm/cmd/add/device` does not support `prefer_img_ver`. `prefer_img_ver` is in the responses, not in the request filed.
So you may need to run `fmgr_dvmdb_workspace_commit_dev `after adding the model device.


PS: For both FortiManager ansible collection and FortiAnalyzer ansible collection, you can set bypass_validation: true to avoid the validation check from the ansible side. So if you are sure that dvm/cmd/add/device supports prefer_img_ver, you can set 
```
fortinet.fortimanager.fmgr_dvm_cmd_add_device:
  bypass_validation: true
  dvm_cmd_add_device:
    adom: "{{ adom_name | lower }}"
      device:
        prefer_img_ver: "{{ device_fos_img_ver }}"
```
And fortimanager ansible collection will send the value of prefer_img_ver to the FortiManager.

If your input arguments are incorrect, sometimes you may get an error, sometimes you will not and the fortimanager would just ignore the incorrect arguments. It is depending on how FortiManager APIs handle input arguments.
