### ISSUE TITLE
Not able to change device hostname using fmgr_dvmdb_device

### ISSUE THREAD

**Issue by cr0cdev** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#72]
Hi!

I'm adding a model device to FortiManager using `fmgr_dvm_cmd_add_device` and after the model device is added I'm trying to change the model device hostname using `fmgr_dvmdb_device`, but it does change the device hostname however when I try to commit the changes to device or commit changes to ADOM then the device hostname is reverted back to original one (_SN_).
I also tried to change the hostname using `fmgr_generic` and url `pm/config/device/{{ device_name | lower }}/global/system/global` and adding name in data. Using `fmgr_generic` the hostname is changed and is not reverted back to original when installing changes.
Also I want to mention that the same behaviour happens with a real device that is online in FMG as well.

What could cause this behaviour or am I using incorrect module to change the device hostname?

Tasks:
```
---
# Add new model device to ADOM "{{ adom_name | lower }}", model device name "{{ device_name | lower }}", serial number "{{ serial_number | upper }}"
- name: Add new model device to ADOM "{{ adom_name | lower }}"
  fortinet.fortimanager.fmgr_dvm_cmd_add_device:
    workspace_locking_adom: "{{ adom_name | lower }}"
    dvm_cmd_add_device:
      adom: "{{ adom_name | lower }}"
      device:
        name: "{{ device_name | lower }}"
        os_ver: "{{ device_fos_ver }}"
        os_type: "{{ device_os_type }}"
        mr: "{{ device_fos_mr }}"
        mgmt_mode: "{{ device_fmg_mgmt_mode }}"
        sn: "{{ serial_number | upper }}"
        device action: "{{ device_action }}"
      flags:
        - "create_task"
        - "nonblocking"
  register: fmg_add_device

# Update model device hostname.
- name: Update the new model devices "{{ device_name | lower }}" hostname and image version in ADOM "{{ adom_name | lower }}"
  fortinet.fortimanager.fmgr_dvmdb_device:
    workspace_locking_adom: "{{ adom_name | lower }}"
    adom: "{{ adom_name | lower }}"
    device: "{{ device_name | lower }}"
    dvmdb_device:
      hostname: "{{ device_name | lower }}"
      prefer_img_ver: "{{ device_fos_img_ver }}"

# Commit chnages to adom
- name: Commit changes to {{ adom_name | lower }}
  fortinet.fortimanager.fmgr_dvmdb_workspace_commit:
    workspace_locking_adom: "{{ adom_name | lower }}"
    adom: "{{ adom_name | lower }}"

# Install changes to device
- name: Commit changes to device
  fortinet.fortimanager.fmgr_securityconsole_install_device:
    workspace_locking_adom: "{{ adom_name | lower }}"
    securityconsole_install_device:
      adom: "{{ adom_name | lower }}"
      scope:
        - name: "{{ device_name | lower }}"
          vdom: "root"
  register: install_device

# Get device install task
- name: Get device install task status
  fortinet.fortimanager.fmgr_fact:
    facts:
      selector: "task_task"
      params:
        task: "{{ install_device.meta.response_data.task }}"
  register: taskinfo
  until: taskinfo.meta.response_data.percent == 100
  retries: 30
  delay: 3
  failed_when: taskinfo.meta.response_data.state == 'error'

```

Results:
`Device hostname is reverted back to original hostname which came from fmgr_dvm_cmd_add_device`
Logs:
```
changed: [fortimanager01] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "access_token": null,
            "bypass_validation": false,
            "dvm_cmd_add_device": {
                "adom": "ansible-test-2",
                "device": {
                    "adm_pass": null,
                    "adm_usr": null,
                    "authorization template": null,
                    "desc": null,
                    "device action": "add_model",
                    "device blueprint": null,
                    "faz.quota": null,
                    "ip": null,
                    "meta fields": null,
                    "mgmt_mode": "fmg",
                    "mr": 2,
                    "name": "fgt40f",
                    "os_type": "fos",
                    "os_ver": "7.0",
                    "patch": null,
                    "platform_str": null,
                    "sn": "FGT40XXXXX"
                },
                "flags": [
                    "create_task",
                    "nonblocking"
                ],
                "groups": null
            },
            "enable_log": false,
            "forticloud_access_token": null,
            "rc_failed": null,
            "rc_succeeded": null,
            "workspace_locking_adom": "ansible-test-2",
            "workspace_locking_timeout": 300
        }
    },
    "meta": {
        "request_url": "/dvm/cmd/add/device",
        "response_code": 0,
        "response_data": {
            "pid": 11019,
            "taskid": 179
        },
        "response_message": "OK",
        "system_information": {
            "Admin Domain Configuration": "Enabled",
            "BIOS version": "04000002",
            "Branch Point": "1460",
            "Build": "1460",
            "Current Time": "Wed Nov 15 15:19:23 EET 2023",
            "Daylight Time Saving": "Yes",
            "FIPS Mode": "Disabled",
            "HA Mode": "Stand Alone",
            "Hostname": "FMG",
            "License Status": "Valid",
            "Major": 7,
            "Max Number of Admin Domains": 2,
            "Max Number of Device Groups": 3,
            "Minor": 2,
            "Offline Mode": "Disabled",
            "Patch": 4,
            "Platform Full Name": "FortiManager-VM64-HV",
            "Platform Type": "FMG-VM64-HV",
            "Release Version Information": " (GA)",
            "Serial Number": "FMG-XXXXX",
            "TZ": "Europe/Helsinki",
            "Time Zone": "(GMT+2:00) Helsinki, Riga,Tallinn.",
            "Version": "v7.2.4-build1460 230926 (GA)",
            "x86-64 Applications": "Yes"
        }
    },
    "rc": 0
}
```
```
changed: [fortimanager01] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "access_token": null,
            "adom": "ansible-test-2",
            "bypass_validation": false,
            "device": "fgt40f",
            "dvmdb_device": {
                "adm_pass": null,
                "adm_usr": null,
                "app_ver": null,
                "av_ver": null,
                "beta": null,
                "branch_pt": null,
                "build": null,
                "checksum": null,
                "conf_status": null,
                "conn_mode": null,
                "conn_status": null,
                "db_status": null,
                "desc": null,
                "dev_status": null,
                "eip": null,
                "fap_cnt": null,
                "faz.full_act": null,
                "faz.perm": null,
                "faz.quota": null,
                "faz.used": null,
                "fex_cnt": null,
                "first_tunnel_up": null,
                "flags": null,
                "foslic_cpu": null,
                "foslic_dr_site": null,
                "foslic_inst_time": null,
                "foslic_last_sync": null,
                "foslic_ram": null,
                "foslic_type": null,
                "foslic_utm": null,
                "fsw_cnt": null,
                "ha_group_id": null,
                "ha_group_name": null,
                "ha_mode": null,
                "ha_slave": null,
                "hdisk_size": null,
                "hostname": "fgt40f",
                "hw_generation": null,
                "hw_rev_major": null,
                "hw_rev_minor": null,
                "hyperscale": null,
                "ip": null,
                "ips_ext": null,
                "ips_ver": null,
                "last_checked": null,
                "last_resync": null,
                "latitude": null,
                "lic_flags": null,
                "lic_region": null,
                "location_from": null,
                "logdisk_size": null,
                "longitude": null,
                "maxvdom": null,
                "meta fields": null,
                "mgmt_id": null,
                "mgmt_if": null,
                "mgmt_mode": null,
                "mgmt_uuid": null,
                "mgt_vdom": null,
                "module_sn": null,
                "mr": null,
                "name": null,
                "nsxt_service_name": null,
                "os_type": null,
                "os_ver": null,
                "patch": null,
                "platform_str": null,
                "prefer_img_ver": "7.2.6-b1575",
                "prio": null,
                "private_key": null,
                "private_key_status": null,
                "psk": null,
                "role": null,
                "sn": null,
                "vdom": null,
                "version": null,
                "vm_cpu": null,
                "vm_cpu_limit": null,
                "vm_lic_expire": null,
                "vm_lic_overdue_since": null,
                "vm_mem": null,
                "vm_mem_limit": null,
                "vm_status": null
            },
            "enable_log": false,
            "forticloud_access_token": null,
            "proposed_method": null,
            "rc_failed": null,
            "rc_succeeded": null,
            "workspace_locking_adom": "ansible-test-2",
            "workspace_locking_timeout": 300
        }
    },
    "meta": {
        "request_url": "/dvmdb/adom/ansible-test-2/device/fgt40f",
        "response_code": 0,
        "response_data": {
            "name": "fgt40f"
        },
        "response_message": "OK",
        "system_information": {
            "Admin Domain Configuration": "Enabled",
            "BIOS version": "04000002",
            "Branch Point": "1460",
            "Build": "1460",
            "Current Time": "Wed Nov 15 15:19:24 EET 2023",
            "Daylight Time Saving": "Yes",
            "FIPS Mode": "Disabled",
            "HA Mode": "Stand Alone",
            "Hostname": "FMG",
            "License Status": "Valid",
            "Major": 7,
            "Max Number of Admin Domains": 2,
            "Max Number of Device Groups": 3,
            "Minor": 2,
            "Offline Mode": "Disabled",
            "Patch": 4,
            "Platform Full Name": "FortiManager-VM64-HV",
            "Platform Type": "FMG-VM64-HV",
            "Release Version Information": " (GA)",
            "Serial Number": "FMG-XXXX",
            "TZ": "Europe/Helsinki",
            "Time Zone": "(GMT+2:00) Helsinki, Riga,Tallinn.",
            "Version": "v7.2.4-build1460 230926 (GA)",
            "x86-64 Applications": "Yes"
        }
    },
    "rc": 0
}
```
```
changed: [fortimanager01] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "access_token": null,
            "adom": "ansible-test-2",
            "bypass_validation": false,
            "enable_log": false,
            "forticloud_access_token": null,
            "rc_failed": null,
            "rc_succeeded": null,
            "workspace_locking_adom": "ansible-test-2",
            "workspace_locking_timeout": 300
        }
    },
    "meta": {
        "request_url": "/dvmdb/adom/ansible-test-2/workspace/commit",
        "response_code": 0,
        "response_data": [],
        "response_message": "OK",
        "system_information": {
            "Admin Domain Configuration": "Enabled",
            "BIOS version": "04000002",
            "Branch Point": "1460",
            "Build": "1460",
            "Current Time": "Wed Nov 15 15:19:25 EET 2023",
            "Daylight Time Saving": "Yes",
            "FIPS Mode": "Disabled",
            "HA Mode": "Stand Alone",
            "Hostname": "FMG",
            "License Status": "Valid",
            "Major": 7,
            "Max Number of Admin Domains": 2,
            "Max Number of Device Groups": 3,
            "Minor": 2,
            "Offline Mode": "Disabled",
            "Patch": 4,
            "Platform Full Name": "FortiManager-VM64-HV",
            "Platform Type": "FMG-VM64-HV",
            "Release Version Information": " (GA)",
            "Serial Number": "FMG-XXXXXX",
            "TZ": "Europe/Helsinki",
            "Time Zone": "(GMT+2:00) Helsinki, Riga,Tallinn.",
            "Version": "v7.2.4-build1460 230926 (GA)",
            "x86-64 Applications": "Yes"
        }
    },
    "rc": 0
}
```
```
changed: [fortimanager01] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "access_token": null,
            "bypass_validation": false,
            "enable_log": false,
            "forticloud_access_token": null,
            "rc_failed": null,
            "rc_succeeded": null,
            "securityconsole_install_device": {
                "adom": "ansible-test-2",
                "dev_rev_comments": null,
                "flags": null,
                "scope": [
                    {
                        "name": "fgt40f",
                        "vdom": "root"
                    }
                ]
            },
            "workspace_locking_adom": "ansible-test-2",
            "workspace_locking_timeout": 300
        }
    },
    "meta": {
        "request_url": "/securityconsole/install/device",
        "response_code": 0,
        "response_data": {
            "task": 180
        },
        "response_message": "OK",
        "system_information": {
            "Admin Domain Configuration": "Enabled",
            "BIOS version": "04000002",
            "Branch Point": "1460",
            "Build": "1460",
            "Current Time": "Wed Nov 15 15:19:26 EET 2023",
            "Daylight Time Saving": "Yes",
            "FIPS Mode": "Disabled",
            "HA Mode": "Stand Alone",
            "Hostname": "FMG",
            "License Status": "Valid",
            "Major": 7,
            "Max Number of Admin Domains": 2,
            "Max Number of Device Groups": 3,
            "Minor": 2,
            "Offline Mode": "Disabled",
            "Patch": 4,
            "Platform Full Name": "FortiManager-VM64-HV",
            "Platform Type": "FMG-VM64-HV",
            "Release Version Information": " (GA)",
            "Serial Number": "FMG-XXXXXX",
            "TZ": "Europe/Helsinki",
            "Time Zone": "(GMT+2:00) Helsinki, Riga,Tallinn.",
            "Version": "v7.2.4-build1460 230926 (GA)",
            "x86-64 Applications": "Yes"
        }
    },
    "rc": 0
}
```
```
ok: [fortimanager01] => {
    "attempts": 1,
    "changed": false,
    "failed_when_result": false,
    "invocation": {
        "module_args": {
            "access_token": null,
            "enable_log": false,
            "facts": {
                "extra_params": null,
                "fields": null,
                "filter": null,
                "option": null,
                "params": {
                    "task": "180"
                },
                "selector": "task_task",
                "sortings": null
            },
            "forticloud_access_token": null,
            "rc_failed": null,
            "rc_succeeded": null,
            "workspace_locking_adom": null,
            "workspace_locking_timeout": 300
        }
    },
    "meta": {
        "request_url": "/task/task/180",
        "response_code": 0,
        "response_data": {
            "adom": 162,
            "end_tm": 1700054366,
            "flags": 0,
            "id": 180,
            "line": [
                {
                    "detail": "Copy to device done",
                    "end_tm": 1700054366,
                    "err": 0,
                    "history": [
                        {
                            "detail": "2023-11-15 15:19:26:Start copying shared objs to devdb, device(fgt40f), vdomid(root)",
                            "name": "fgt40f[copy]",
                            "percent": 1,
                            "vdom": "root"
                        },
                        {
                            "detail": "2023-11-15 15:19:26:Copy done",
                            "name": "fgt40f[copy]",
                            "percent": 90,
                            "vdom": "root"
                        },
                        {
                            "detail": "2023-11-15 15:19:26:Copy to device done",
                            "name": "fgt40f[copy]",
                            "percent": 100,
                            "vdom": "root"
                        }
                    ],
                    "ip": "",
                    "name": "fgt40f[copy]",
                    "oid": 188,
                    "percent": 100,
                    "start_tm": 1700054366,
                    "state": "done",
                    "vdom": "root"
                }
            ],
            "num_done": 1,
            "num_err": 0,
            "num_lines": 1,
            "num_warn": 0,
            "percent": 100,
            "pid": 11037,
            "src": "install device",
            "start_tm": 1700054366,
            "state": "done",
            "title": "Install Device",
            "tot_percent": 100,
            "user": "ansible_admin"
        },
        "response_message": "OK",
        "system_information": {
            "Admin Domain Configuration": "Enabled",
            "BIOS version": "04000002",
            "Branch Point": "1460",
            "Build": "1460",
            "Current Time": "Wed Nov 15 15:19:26 EET 2023",
            "Daylight Time Saving": "Yes",
            "FIPS Mode": "Disabled",
            "HA Mode": "Stand Alone",
            "Hostname": "FMG",
            "License Status": "Valid",
            "Major": 7,
            "Max Number of Admin Domains": 2,
            "Max Number of Device Groups": 3,
            "Minor": 2,
            "Offline Mode": "Disabled",
            "Patch": 4,
            "Platform Full Name": "FortiManager-VM64-HV",
            "Platform Type": "FMG-VM64-HV",
            "Release Version Information": " (GA)",
            "Serial Number": "FMG-XXXXXX",
            "TZ": "Europe/Helsinki",
            "Time Zone": "(GMT+2:00) Helsinki, Riga,Tallinn.",
            "Version": "v7.2.4-build1460 230926 (GA)",
            "x86-64 Applications": "Yes"
        }
    },
    "rc": 0
}
```

Expected result:
`Device hostname has been changed.`
