### ISSUE TITLE
Failed login username and password FMG 7.0.2 and 7.2.4

### ISSUE THREAD

**Issue by PieBee123** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#74]
Hi,

Looking for some help, need to access the Fortimanager API with Ansible to check the device sync of the Fortigates. Only the problem is I'm unable to connected to the FortiManager with the ansible galaxy with a normal curl everything is working. Or the playbook and a FortiManager with 7.2.4 and api-token is working fine.

I amuse my problem is a small thing only i don't see it any more, i use ansible-galaxy collection 'fortinet.fortimanager  2.3.0'. 

Looking forward for some help.
## Code:
    ---
    - name: gathering fortimanager facts
      hosts: fortimanager
      gather_facts: no
      connection: httpapi
      collections:
        - fortinet.fortimanager
      vars:
        ansible_httpapi_use_ssl: True
        ansible_httpapi_validate_certs: False
        ansible_httpapi_port: 443
        ansible_network_os: fortinet.fortimanager.fortimanager
        ansible_user: '***'
        ansible_password: '***'
      tasks:
        - name: Display response
          debug:
            var: ansible_user
    
        - name: Log into the device with user name and password.
          fmgr_sys_login_user:
            #bypass_validation: False
            #workspace_locking_adom: <value in [global, custom adom including root]>
            #workspace_locking_timeout: 300
            #rc_succeeded: [0, -2, -3, ...]
            #rc_failed: [-2, -3, ...]
            sys_login_user:
              passwd: "{{ ansible_password }}"
              user: "{{ ansible_user }}"
---
## Playbook error:
---
TASK [Log into the device with user name and password.] *********************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: Can't login. Your login method is username_password. Please check whether you provide the correct information.
fatal: [gsd_fmg]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/***/.ansible/tmp/ansible-local-1929518nk519jag/ansible-tmp-1701782642.979202-1929530-172595902216755/AnsiballZ_fmgr_sys_login_user.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/***/.ansible/tmp/ansible-local-1929518nk519jag/ansible-tmp-1701782642.979202-1929530-172595902216755/AnsiballZ_fmgr_sys_login_user.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/***/.ansible/tmp/ansible-local-1929518nk519jag/ansible-tmp-1701782642.979202-1929530-172595902216755/AnsiballZ_fmgr_sys_login_user.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.fortinet.fortimanager.plugins.modules.fmgr_sys_login_user', init_globals=dict(_module_fqn='ansible_collections.fortinet.fortimanager.plugins.modules.fmgr_sys_login_user', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_fmgr_sys_login_user_payload_yswvjz03/ansible_fmgr_sys_login_user_payload.zip/ansible_collections/fortinet/fortimanager/plugins/modules/fmgr_sys_login_user.py\", line 397, in <module>\n  File \"/tmp/ansible_fmgr_sys_login_user_payload_yswvjz03/ansible_fmgr_sys_login_user_payload.zip/ansible_collections/fortinet/fortimanager/plugins/modules/fmgr_sys_login_user.py\", line 388, in main\n  File \"/tmp/ansible_fmgr_sys_login_user_payload_yswvjz03/ansible_fmgr_sys_login_user_payload.zip/ansible_collections/fortinet/fortimanager/plugins/module_utils/napi.py\", line 162, in __init__\n  File \"/tmp/ansible_fmgr_sys_login_user_payload_yswvjz03/ansible_fmgr_sys_login_user_payload.zip/ansible_collections/fortinet/fortimanager/plugins/module_utils/napi.py\", line 342, in get_system_status\n  File \"/tmp/ansible_fmgr_sys_login_user_payload_yswvjz03/ansible_fmgr_sys_login_user_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: Can't login. Your login method is username_password. Please check whether you provide the correct information.\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by dux-fortinet** [comment]
Hi PieBee123,

The playbook you provided works well in my test environment.

The FortiManager Ansible Collection will automatically log in to the FortiManager once you specify the variable ansible_user and ansible_password and it will automatically log out when all tasks are completed. So you don't need to call fmgr_sys_login_user to log in. (And it is fine if you call it, the playbook should still work well)

In your playbook, the FortiManager Ansible Collection will call API '/sys/login/user' twice. The first one is automation log in by FMG Ansible Collection, and the second time is because of the task fmgr_sys_login_user. Based on the playbook error, it seems the FortiManager Ansible Collection can't use the username and password you provided to log in in the first time.  

That is all I can tell from the playbook error. I can't figure out what caused this error. You can get more debug information by adding "enable_log: true" under `fmgr_sys_login_user:`, and the debug data will be appended to the file `/tmp/fortimanager.ansible.log`

Here is an example:
```
    - name: Log into the device with user name and password.
      fmgr_sys_login_user:
        enable_log: true
        sys_login_user:
          passwd: "{{ ansible_password }}"
          user: "{{ ansible_user }}"
```

And you don't need to use fmgr_sys_login_user since FMG Ansible Collection will do it for you automatically. So you can directly run some other tasks, like create a new adom:
FILE: example.yml
```
- hosts: fortimanagers
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    - name: ADOM table, most attributes are read-only and can only be changed internally.
      fmgr_dvmdb_adom:
        bypass_validation: True
        enable_log: True
        state: present
        dvmdb_adom:
          desc: Created by Ansible
          name: ansible_adom
```
FILE: host
```
[fortimanagers]
fortimanager_name ansible_host=192.168.0.100 ansible_user="***" ansible_password="***"

[fortimanagers:vars]
ansible_network_os=fortinet.fortimanager.fortimanager
```
COMMAND:  ansible-playbook -i hosts ./example.yml
