### ISSUE TITLE
fmgr_dvmdb_workspace_commit_dev fails with workspace lock

### ISSUE THREAD

**Issue by cr0cdev** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#78]
Hi!

I think I've found a interesting bug. When I try to commit changes the the device using `fmgr_dvmdb_workspace_commit_dev` with or without `workspace_locking_adom` it fails with error "Workspace is locked by other user" even though the workspace is not locked by other user. I've tried to unlock the workspace with `fmgr_dvmdb_workspace_unlock` and locking it with `workspace_locking_adom` and `fmgr_dvmdb_workspace_lock`. In this case both fail as well with the same error.

This is the task:
```
---
- name: Unlocking ADOM from workspace mode
  fortinet.fortimanager.fmgr_dvmdb_workspace_unlock:
    adom: "{{ adom_name | lower }}"

- name: Check if ADOM {{ adom_name | lower }} is locked or unlocked
  when: adom_check.meta.response_code == 0 and adom_check.meta.response_message == "OK"
  block:
    - name: Check lock status
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "dvmdb_workspace_lockinfo"
          params:
            adom: "{{ adom_name | lower }}"

- name: Commit changes to {{ adom_name | lower }}
  fortinet.fortimanager.fmgr_dvmdb_workspace_commit_dev:
    workspace_locking_adom: "{{ adom_name | lower }}"
    adom: "{{ adom_name | lower }}"
    device_name: "{{ device_name | lower }}"

- name: Installing device configurations
  fortinet.fortimanager.fmgr_securityconsole_install_device:
    workspace_locking_adom: "{{ adom_name | lower }}"
    securityconsole_install_device:
      adom: "{{ adom_name | lower }}"
      scope:
        - name: "{{ device_name | lower }}"
          vdom: "root"
  register: install_device
  
- name: Poll the install_device status
  when: install_device is changed
  block:
    - name: Poll the "install_device" status
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "task_task"
          params:
            task: "{{ install_device.meta.response_data.task }}"
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5
      failed_when: (taskinfo.meta.response_data.state == 'error') or (taskinfo.attempts >= 30)
  rescue:
    - name: Create error message file
      file:
        path: error.txt
        mode: "0755"
        state: touch
    - name: Write error message to file
      lineinfile:
        path: error.txt
        line: "Please contact technical support and send them the task ID: {{ taskinfo.meta.response_data.id }}"
    - name: Fail task after file creation
      fail:
        msg: "Check error file for the reason why task failed"
```
ADOM lock info:
```
ok: [fortimanager01] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_token": null,
            "enable_log": false,
            "facts": {
                "extra_params": null,
                "fields": null,
                "filter": null,
                "option": null,
                "params": {
                    "adom": "ansible-test-1"
                },
                "selector": "dvmdb_workspace_lockinfo",
                "sortings": null
            },
            "forticloud_access_token": null,
            "rc_failed": null,
            "rc_succeeded": null,
            "workspace_locking_adom": null,
            "workspace_locking_timeout": 300
        }
    },
    "meta": {
        "request_url": "/dvmdb/adom/ansible-test-1/workspace/lockinfo",
        "response_code": 0,
        "response_data": [],
        "response_message": "OK",
        "system_information": {
            "Admin Domain Configuration": "Enabled",
            "BIOS version": "04000002",
            "Branch Point": "1460",
            "Build": "1460",
            "Current Time": "Thu Jan 04 17:16:38 EET 2024",
            "Daylight Time Saving": "Yes",
            "FIPS Mode": "Disabled",
            "HA Mode": "Stand Alone",
            "Hostname": "FMG",
            "License Status": "Valid",
            "Major": 7,
            "Max Number of Admin Domains": 2,
            "Max Number of Device Groups": 3,
            "Minor": 2,
            "Offline Mode": "Disabled",
            "Patch": 4,
            "Platform Full Name": "FortiManager-VM64-HV",
            "Platform Type": "FMG-VM64-HV",
            "Release Version Information": " (GA)",
            "Serial Number": "FMG-XXXXXX",
            "TZ": "Europe/Helsinki",
            "Time Zone": "(GMT+2:00) Helsinki, Riga,Tallinn.",
            "Version": "v7.2.4-build1460 230926 (GA)",
            "x86-64 Applications": "Yes"
        }
    },
    "rc": 0
}
```
Error when commiting to the device:
```
fatal: [fortimanager01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_token": null,
            "adom": "ansible-test-1",
            "bypass_validation": false,
            "device_name": "fgt60f",
            "enable_log": false,
            "forticloud_access_token": null,
            "rc_failed": null,
            "rc_succeeded": null,
            "workspace_locking_adom": "ansible-test-1",
            "workspace_locking_timeout": 300
        }
    },
    "meta": {
        "request_url": "/dvmdb/adom/ansible-test-1/workspace/commit/dev/fgt60f",
        "response_code": -20055,
        "response_data": [],
        "response_message": "Workspace is locked by other user",
        "system_information": {
            "Admin Domain Configuration": "Enabled",
            "BIOS version": "04000002",
            "Branch Point": "1460",
            "Build": "1460",
            "Current Time": "Thu Jan 04 17:16:40 EET 2024",
            "Daylight Time Saving": "Yes",
            "FIPS Mode": "Disabled",
            "HA Mode": "Stand Alone",
            "Hostname": "FMG",
            "License Status": "Valid",
            "Major": 7,
            "Max Number of Admin Domains": 2,
            "Max Number of Device Groups": 3,
            "Minor": 2,
            "Offline Mode": "Disabled",
            "Patch": 4,
            "Platform Full Name": "FortiManager-VM64-HV",
            "Platform Type": "FMG-VM64-HV",
            "Release Version Information": " (GA)",
            "Serial Number": "FMG-XXXXXXXX",
            "TZ": "Europe/Helsinki",
            "Time Zone": "(GMT+2:00) Helsinki, Riga,Tallinn.",
            "Version": "v7.2.4-build1460 230926 (GA)",
            "x86-64 Applications": "Yes"
        }
    },
    "rc": -20055
}
```

**Comment by MaxxLiu22** [comment]
Hi @cr0cdev ,

Thank you for raising this question. When workspace mode enabled, we have to lock the target object before edit it, "adom lock" and "device lock" are two different scope locks, our Ansible modules currently support automatically lock and unlock adom by setting ``workspace_locking_adom``, if we would like to commit a device, we have to lock and unlock the device manually, otherwise we may not have the permission to make any operations on it. could you add lock and unlock device operations before and after your commit operation like the following script, let me know if that doesn't solve your question.
```
  - name: lock
    fortinet.fortimanager.fmgr_dvmdb_workspace_lock_dev:
      # workspace_locking_adom: "test"
      adom: "test"
      device_name: "FGVMULTM23002193"

  - name: Commit
    fortinet.fortimanager.fmgr_dvmdb_workspace_commit_dev:
      # workspace_locking_adom: "test"
      adom: "test"
      device_name: "FGVMULTM23002193"

  - name: unlock
    fortinet.fortimanager.fmgr_dvmdb_workspace_unlock_dev:
      # workspace_locking_adom: "test"
      adom: "test"
      device_name: "FGVMULTM23002193"
```

Thanks,
Maxx
