### ISSUE TITLE
Creating a firewall custom service with fmgr_firewall_service_custom module returns the code -10: The data is invalid for selected url

### ISSUE THREAD

**Issue by albertogd** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#79]
Hi,

I'm trying to create a firewall custom service with the module `fmgr_firewall_service_custom`, but it's failing, returning the code -10 and the message  "_The data is invalid for selected url_"

This the code (just adding the parameters from the module example):

```
- name: Configure custom services.
  fmgr_firewall_service_custom:
     bypass_validation: False
     access_token: "{{fortitoken}}"
     adom: BACKBONE
     state: present
     firewall_service_custom:
        app-service-type: disable
        color: 1
        comment: 'comment'
        helper: auto
        name: 'ansible-test'
        protocol: ALL
        proxy: enable
        visibility: enable
```

And this is the response:

`fatal: [fortimanagerip]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "adom": "BACKBONE",
            "bypass_validation": false,
            "enable_log": false,
            "firewall_service_custom": {
                "app-category": null,
                "app-service-type": "disable",
                "application": null,
                "category": "ansible-test",
                "check-reset-range": null,
                "color": 1,
                "comment": "comment",
                "explicit-proxy": null,
                "fabric-object": null,
                "fqdn": null,
                "global-object": null,
                "helper": "auto",
                "icmpcode": null,
                "icmptype": null,
                "iprange": null,
                "name": "ansible-test",
                "protocol": "ALL",
                "protocol-number": null,
                "proxy": "enable",
                "sctp-portrange": null,
                "session-ttl": null,
                "tcp-halfclose-timer": null,
                "tcp-halfopen-timer": null,
                "tcp-portrange": null,
                "tcp-rst-timer": null,
                "tcp-timewait-timer": null,
                "udp-idle-timer": null,
                "udp-portrange": null,
                "visibility": "enable"
            },
            "forticloud_access_token": null,
            "proposed_method": null,
            "rc_failed": null,
            "rc_succeeded": null,
            "state": "present",
            "workspace_locking_adom": null,
            "workspace_locking_timeout": 300
        }
    },
    "meta": {
        "request_url": "/pm/config/adom/BACKBONE/obj/firewall/service/custom",
        "response_code": -10,
        "response_data": [],
        "response_message": "The data is invalid for selected url",
        "system_information": {
            "Admin Domain Configuration": "Disabled",
            "BIOS version": "04000002",
            "Branch Point": "2397",
            "Build": "2397",
            "Current Time": "Wed Jan 17 04:59:03 PST 2024",
            "Daylight Time Saving": "Yes",
            "FIPS Mode": "Disabled",
            "HA Mode": "Stand Alone",
            "Hostname": "FMG-VM64-KVM",
            "License Status": "Valid",
            "Major": 7,
            "Max Number of Admin Domains": 10,
            "Max Number of Device Groups": 10,
            "Minor": 4,
            "Offline Mode": "Disabled",
            "Patch": 2,
            "Platform Full Name": "FortiManager-VM64-KVM",
            "Platform Type": "FMG-VM64-KVM",
            "Release Version Information": " (GA)",
            "Serial Number": "FMG-VM0000000000",
            "TZ": "US/Pacific",
            "Time Zone": "(GMT-8:00) Pacific Time (US & Canada).",
            "Version": "v7.4.2-build2397 231220 (GA)",
            "x86-64 Applications": "Yes"
        }
    },
    "rc": -10
}
`

Is there anything I need to create before, or any parameter wrong/missing?

Using uri module (with all the configuration I need):

```
- name: Create new services TCP UDP SCP
  uri:
    url: https://{{ansible_host}}/jsonrpc?access_token={{fortitoken}}
    method: POST
    body:
      {
        "method": "add",
        "params":
        [
          {
            "data":
            {
              "category":["{{item.category}}"],
              "app-service-type": 0,
              "check-reset-range": 3,
              "color": 0,
              "fabric-object": 0,
              "helper": 1,
              "iprange": "0.0.0.0",
              "name": "{{item.servicename}}",
              "protocol": "{{item.protocolnumber}}",
              "proxy": 0,
              "sctp-portrange": "{{item.sctpportrange}}",
              "session-ttl": "0",
              "tcp-halfclose-timer": 0,
              "tcp-halfopen-timer": 0,
              "tcp-portrange": "{{item.tcpportrange}}",
              "tcp-rst-timer": 0,
              "tcp-timewait-timer": 0,
              "udp-idle-timer": 0,
              "udp-portrange": "{{item.udpportrange}}",
              "visibility": 1
            },
            "revision note": "Configured by Ansible",
            "url": "pm/config/adom/{{item.adomname}}/obj/firewall/service/custom"
          }
        ]
      }
    body_format: json
    status_code: 200
    validate_certs: False
  loop: "{{conffile.service}}"
```

**Comment by dux-fortinet** [comment]
Hi albertogd,

The first playbook your provided works well in my environment. 
Please share the log data so that I can figure out what is the cause: add **enable_log: true** in your playbook, and the log data will be appended to the file **/tmp/fortimanager.ansible.log**.

Since the log data is appended to the file, please remember to clear the file /tmp/fortimanager.ansible.log before you start a new log.
```
- name: Configure custom services.
  fmgr_firewall_service_custom:
     bypass_validation: False
     enable_log: true  # enable log
     access_token: "{{fortitoken}}"
     adom: BACKBONE
     state: present
     firewall_service_custom:
        app-service-type: disable
        color: 1
        comment: 'comment'
        helper: auto
        name: 'ansible-test'
        protocol: ALL
        proxy: enable
        visibility: enable
```

Please share the whole log file or the log data containing the string "obj/firewall/service/custom/". Thanks :)
