### ISSUE TITLE
Support "Enforce firmware" when adding model device

### ISSUE THREAD

**Issue by cr0cdev** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#81]
Hi!

Is it possible to support `Enforce firmware` setting when adding model device so it is possible to let FMG know that it should use syntax that is supported by older FGT firmware.
Example:
When adding FGT to FMG which is running older FOS then we might need to enforce a certain FOS version so FMG wouldn't use new syntax's that are not supported by older FOS version. Sometimes a new web filter categories are released for example and they are not supported by older FOS versions, but without using enforce firmware setting when adding model device the FMG will use latest syntax's and also will try to push new web filter categories to the FGT, but when doing that the config push fails since older FOS does not know about those new web filter categories or syntax's.

I'm not sure that API supports it, but when looking at network requests when adding the model device it seems that the API request sent via GUI is using `preferred_img_ver` as a parameter for the `Enforce firmware` setting. There is a internal bug report going on with FMG 7.2.5 already _there is a issue with new web filter categories and FOS versions older than 7.2.8_.

Thanks!

**Comment by dux-fortinet** [comment]
Hi @cr0cdev,

Adding device using the API `dvm/cmd/add/device`.
I can't find the parameter `preferred_img_ver` for API `dvm/cmd/add/device` in the FNDN. Yet according to my experiment, when you add a device through GUI and enable `Enforce firmware`, the web will send a JSON request like the following, and `preferred_img_ver` indeed appears in the JSON request.

```
{
    "method": "exec",
    "params": [
        {
            "url": "dvm/cmd/add/device",
            "data": {
                "adom": "root",
                "flags": [
                    "create_task",
                    "nonblocking"
                ],
                "device": {
                    "name": "TEST",
                    "adm_usr": "admin",
                    "os_ver": 7,
                    "version": 700,
                    "os_type": 0,
                    "mr": 2,
                    "platform_str": "FortiGate-VM64",
                    "platform_id": 150,
                    "mgmt_mode": 3,
                    "prefer_img_ver": "7.2.4-b1396",
                    "build": 1396,
                    "branch_pt": 1396,
                    "sn": "FGVMMLTMXXXXXX",
                    "flags": 67371040,
                    "faz.perm": 15,
                    "faz.quota": 0
                }
            }
        }
    ]
}
```

I will support `preferred_img_ver` in the next release version.
(And I will do more experiments to figure out whether we need to support more parameters for the `Enforce firmware` setting)

Thanks,
Xinwei

**Comment by dux-fortinet** [comment]
Hi cr0cdev,

I rerun the whole experiment today in 3 different ways: GUI, JSON request, and Ansible. It seems FMG will automatically detect the version of FGT.

For the GUI side, if you click "Device Manager -> Device & Groups -> Add Device", it will show you several ways to add a device. If you choose "Add Model Device" (To add a device that is not yet online), you may set "Enforce Firmware" because it is for the offline FGT, and the FMG doesn't know its version yet. However, if you choose "Discover Device"(To add a device that is currently online), you can't find the "Enforce Firmware" selection, all you need is FGT IP address (and username, and password for FGT).

Same for the JSON request. Here is the example JSON request that I used.
```
{
    "method": "exec",
    "params": [
        {
            "url": "/dvm/cmd/add/device",
            "data": {
                "adom": "root",
                "device": {
                    "adm_pass": "example_passwd",
                    "adm_usr": "admin",
                    "desc": "",
                    "ip": "10.160.88.155",
                    "mgmt_mode": "fmg",
                    "name": "FGVMMLTM00000000",
                    "sn": "FGVMMLTM00000000",
                    "preferred_img_ver": "7.2.5-b1517"
                },
                "flags": [
                    "create_task",
                    "nonblocking"
                ]
            }
        }
    ],
    "session": "xxxxxxx",
    "id": 8,
    "verbose": 1
}
```
The FGT I want to add is v7.2.4, I used `preferred_img_ver` in this request and set it as "7.2.5-b1517" (so I want to set `Enforce firmware`), however, after the device is added, from the FMG side, the FGT system version is still v7.2.4. I tried to get data from "url": "/dvmdb/device", the "preferred_img_ver" of this FGT is "".

I haven't figured out how to support `Enforce firmware`.
Yet the next version of FortiManager Ansible Collection will allow you to send any parameter to FMG by setting "bypass_validation: true". Currently, bypass_validation is only for ignoring parameter type validation checks. (If one parameter in the new FMG changed from string type to a list of strings, while Ansible Collection still requires this parameter to be a string, you can set bypass_validation: true to ignore parameter type check.)

In the next version of FortiManager Ansible Collection, if you set "bypass_validation: true", you can also send any parameter that does not appear in the FNDN (such as `preferred_img_ver`). So in the future, if we figure out that parameter related to `Enforce firmware`, you don't need to wait for a new FMG Ansible Collection update, you can send that parameter to FMG directly by setting "bypass_validation: true" to avoid validation check from Ansible.

Example of Ansible Playbook
```
- name: Add a FOS device to FMG
  hosts: fortimanagers
  gather_facts: false
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
    fos_user: "admin"
    fos_pass: "example_passwd"
    fos_ip: "192.160.0.123"
  tasks:
    - name: Discover device
      fortinet.fortimanager.fmgr_dvm_cmd_discover_device:
        dvm_cmd_discover_device:
          device:
            adm_pass: "{{ fos_pass }}"
            adm_usr: "{{ fos_user }}"
            ip: "{{ fos_ip }}"
      register: probed_device
    - name: Show system_status
      ansible.builtin.debug:
        msg: "{{ probed_device }}"
    - name: Add device
      fortinet.fortimanager.fmgr_dvm_cmd_add_device:
        bypass_validation: true # bypass_validation: true to allow you send any parameter not in the FNDN schema.
        dvm_cmd_add_device:
          adom: "root"
          flags:
            - "create_task"
            - "nonblocking"
          device:
            adm_usr: "{{ probed_device.meta.response_data.device.adm_usr }}"
            adm_pass: "{{ fos_pass }}"
            desc: "The device is added via FortiManager Ansible"
            ip: "{{ probed_device.meta.response_data.device.ip }}"
            mgmt_mode: "fmg"
            name: "{{ probed_device.meta.response_data.device.name }}"
            sn: "{{ probed_device.meta.response_data.device.sn }}"
            preferred_img_ver: "7.2.5-b1517"
            other_param_not_in_FNDN: "your_value"
      register: installing_task
    - name: Poll the task
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "task_task"
          params:
            task: "{{ installing_task.meta.response_data.taskid }}"
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5
      failed_when: taskinfo.meta.response_data.state == 'error' and 'devsnexist' not in taskinfo.meta.response_data.line[0].detail
```
