### ISSUE TITLE
State "absent" not supported by fmgr_pm_pkg_scopemember

### ISSUE THREAD

**Issue by cr0cdev** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#82]
Hi!

I've found out that `fmgr_pm_pkg_scopemember` does not support `state: absent` parameter even though the documentation says it is supported.
This is what I get when I try to remove a ADOM from global policy after unassigning the policy from ADOM.
Task:
```
- name: Remove ADOM from global policy
  fortinet.fortimanager.fmgr_pm_pkg_scopemember:
    workspace_locking_adom: "global"
    adom: "global"
    pkg_path: "{{ global_policy }}"
    state: absent
    pm_pkg_scopemember:
      name: "{{ adom_name | lower }}"
``` 
Response:
```
fatal: [fortimanager01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_token": null,
            "adom": "global",
            "bypass_validation": false,
            "enable_log": false,
            "forticloud_access_token": null,
            "pkg_path": "GLOBAL-POLICY",
            "pm_pkg_scopemember": {
                "name": "ansible-test",
                "vdom": null
            },
            "proposed_method": null,
            "rc_failed": null,
            "rc_succeeded": null,
            "state": "absent",
            "workspace_locking_adom": "global",
            "workspace_locking_timeout": 300
        }
    },
    "msg": "This module doesn't not support state:absent yet."
}

``` 

Not sure if `fmgr_pm_pkg_scopemember` only supports ADOM level policy members (_devices_) or it also supports removing ADOM from global policy.

Thanks!
