### ISSUE TITLE
fmgr_securityconsole_install_preview - Don't report modifications present on ADOM

### ISSUE THREAD

**Issue by apellini** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#91]
Fortimanager
`
6.4.10
`

Ansible Version
```
ansible [core 2.14.15]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.19 (main, Mar 30 2024, 17:38:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] (/usr/local/bin/python3.9)
  jinja version = 3.1.3
  libyaml = True
```

OS Version
`
Red Hat Enterprise Linux Server release 7.9 (Maipo)
`

Collections version
`
fortinet.fortimanager         2.2.0
`

Problem description
Using following playbook

```yaml
- name: INSTALL PREVIEW - POLICY PACKAGE
  hosts: fmg
  connection: httpapi
  vars:
    adom: demo
    ppkg: ppkg_hubs
    device: fgt_00_1
  tasks:
    - name: Install for policy package [preview mode] {{ ppkg }}
      fortinet.fortimanager.fmgr_securityconsole_install_package:
        securityconsole_install_package:
          adom: "{{ adom }}"
          flags:
            - preview
          pkg: "{{ ppkg }}"
          scope:
            - name: "{{ device }}"
      register: r
    - name: Poll the task
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "task_task"
          params:
            task: "{{ r.meta.response_data.task }}"
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5
    - name: Trigger the preview report generation for policy package {{ ppkg }}
      fortinet.fortimanager.fmgr_securityconsole_install_preview:
        securityconsole_install_preview:
          adom: "{{ adom }}"
          device: "{{ device }}"
          flags:
            - json
      register: r
    - name: Poll the task
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "task_task"
          params:
            task: "{{ r.meta.response_data.task }}"
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5
    - name: Get the preview report for policy package {{ ppkg }}
      fortinet.fortimanager.fmgr_securityconsole_preview_result:
        securityconsole_preview_result:
          adom: "{{ adom }}"
          device: "{{ device }}"
      register: r
    - name: Cancel install task for policy package {{ ppkg }}
      fortinet.fortimanager.fmgr_securityconsole_package_cancel_install:
        securityconsole_package_cancel_install:
          adom: "{{ adom }}"
    - name: Show preview report
      ansible.builtin.debug:
        msg: "{{ r }}"
```

We have done some modifications on our ADOM but output given by r variable is reporting an empty response.

Below an example of debug task:

```
TASK [Show preview report] *****************************************************************************************************************************************************************************************************************
ok: [fmg] => {
    "msg": {
        "changed": true,
        "failed": false,
        "meta": {
            "request_url": "/securityconsole/preview/result",
            "response_code": 0,
            "response_data": {
                "message": ""
            },
            "response_message": "OK",
            "system_information": {
                "Admin Domain Configuration": "Enabled",
                "BIOS version": "XXXXXXXX",
                "Branch Point": "XXXX",
                "Build": "XXXX",
                "Current Time": "Wed Nov 13 17:47:01 XXX 2024",
                "Daylight Time Saving": "Yes",
                "FIPS Mode": "Disabled",
                "HA Mode": "XXXXXXX",
                "Hostname": "fmg",
                "Major": 6,
                "Max Number of Admin Domains": XXX,
                "Max Number of Device Groups": XXX,
                "Minor": 4,
                "Offline Mode": "Disabled",
                "Patch": 10,
                "Platform Full Name": "FortiManager-XXXX",
                "Platform Type": "FMGXXXXX",
                "Release Version Information": " (GA)",
                "Serial Number": "sdasdsa",
                "System Part-Number": "XXXXXXX",
                "Time Zone": "XXXXXXXXXX,
                "Version": "v6.4.10-build2549 221103 (GA)",
                "x86-64 Applications": "Yes"
            }
        },
        "rc": 0
    }
}
```

Our scope is to discover if pending configuration are present before doing any configuration activities. If there is any other solution to solve this use case is appreciated.

**Comment by apellini** [comment]
Any update on this?

**Comment by MaxxLiu22** [comment]
Hi @apellini ,

Thank you for bringing this issue to my attention, and I sincerely apologize for the delayed response. Upon reviewing your script and checking the task monitor, it seems the issue might be due to the root VDOM not being defined, which could cause the package preview to fail. After adding ``vdom: "root"`` to your first task scope, my preview results displayed the expected difference, specifically a policy name change. Please let me know if this does not fully address your concern, and I’ll be happy to assist further.
<img width="953" alt="image" src="https://github.com/user-attachments/assets/1fc47e0d-9b04-451b-8908-214fdd8ac1e2">
```
  tasks:
    - name: Install for policy package [preview mode] {{ ppkg }}
      fortinet.fortimanager.fmgr_securityconsole_install_package:
        securityconsole_install_package:
          adom: "{{ adom }}"
          flags:
            - preview
          pkg: "{{ ppkg }}"
          scope:
            - name: "{{ device }}"
              vdom: "root"   <--------------------------
      register: r
```
```
TASK [Poll the task] *************************************************************************************************************************************************************************************************
FAILED - RETRYING: [fortimanager01]: Poll the task (30 retries left).
FAILED - RETRYING: [fortimanager01]: Poll the task (29 retries left).
ok: [fortimanager01]

TASK [Get the preview report for policy package pkg] *****************************************************************************************************************************************************************
changed: [fortimanager01]

TASK [Cancel install task for policy package pkg] ********************************************************************************************************************************************************************
changed: [fortimanager01]

TASK [Show preview report] *******************************************************************************************************************************************************************************************
ok: [fortimanager01] => {
    "msg": {
        "changed": true,
        "failed": false,
        "meta": {
            "request_url": "/securityconsole/preview/result",
            "response_code": 0,
            "response_data": {
                "message": "config firewall policy\n    edit 1\n        set name \"test2\"\n    next\nend\n"
            },
            "response_message": "OK",
            "system_information": {
                "Admin Domain Configuration": "Disabled",
                "BIOS version": "04000002",
                "Branch Point": "2549",
                "Build": "2549",
                "Current Time": "Mon Nov 18 14:00:26 PST 2024",
                "Daylight Time Saving": "Yes",
                "FIPS Mode": "Disabled",
                "HA Mode": "Stand Alone",
                "Hostname": "FGT-VM-106",
                "License Status": "Valid",
                "Major": 6,
                "Max Number of Admin Domains": 10000,
                "Max Number of Device Groups": 10000,
                "Minor": 4,
                "Offline Mode": "Disabled",
                "Patch": 10,
                "Platform Full Name": "FortiManager-VM64-KVM",
                "Platform Type": "FMG-VM64-KVM",
                "Release Version Information": " (GA)",
                "Serial Number": "FMG-VMTM24012097",
                "Time Zone": "(GMT-8:00) Pacific Time (US & Canada).",
                "Version": "v6.4.10-build2549 221103 (GA)",
                "x86-64 Applications": "Yes"
            }
        },
        "rc": 0
    }
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************
fortimanager01             : ok=9    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```
Thanks,
Maxx

**Comment by dux-fortinet** [comment]
Hi @apellini,

I think the problem comes from the backend API of the module `fmgr_securityconsole_install_package`. For some unknown reasons, the FortiManager can't find the Installation Targets even if you have specified the "scope” in `fmgr_securityconsole_install_package`. 
I have found a workaround, and I can use `fmgr_securityconsole_install_package` without specifying `scope`, and FortiManager can detect the Installation Targets correctly.

You can use the module `fmgr_pm_pkg_adom` to bind your device to a target pkg, and then, you can use `fmgr_securityconsole_install_package` without specifying the variable `scrop`.

The following script works well in my environment (FMG 6.4.10, FGT 6.4.10)
```
- name: GitHub91
  hosts: fortimanagers
  connection: httpapi
  vars:
    adom: root
    ppkg: <YOUR-PKG-NAME>
    device: FGVMULTMXXXXXXXX
    vdom: root
  tasks:
    - name: Add your {{ device }}-{{ vdom }} to pkg {{ ppkg }}
      fortinet.fortimanager.fmgr_pm_pkg_adom:
        adom: "{{ adom }}"
        pm_pkg_adom:
          name: "{{ ppkg }}"
          scope_member:
            - name: "{{ device }}"
              vdom: "{{ vdom }}"
    - name: Install for policy package [preview mode] {{ ppkg }}
      fortinet.fortimanager.fmgr_securityconsole_install_package:
        securityconsole_install_package:
          adom: "{{ adom }}"
          flags:
            - preview
          pkg: "{{ ppkg }}"
      register: r
    - name: Poll the task
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "task_task"
          params:
            task: "{{ r.meta.response_data.task }}"
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5

    - name: Trigger the preview report generation for policy package {{ ppkg }}
      fortinet.fortimanager.fmgr_securityconsole_install_preview:
        securityconsole_install_preview:
          adom: "{{ adom }}"
          device: "{{ device }}"
          flags:
            - json
      register: r
    - name: Poll the task
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "task_task"
          params:
            task: "{{ r.meta.response_data.task }}"
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5

    - name: Get the preview report for policy package {{ ppkg }}
      fortinet.fortimanager.fmgr_securityconsole_preview_result:
        securityconsole_preview_result:
          adom: "{{ adom }}"
          device: "{{ device }}"
      register: r
    - name: Cancel install task for policy package {{ ppkg }}
      fortinet.fortimanager.fmgr_securityconsole_package_cancel_install:
        securityconsole_package_cancel_install:
          adom: "{{ adom }}"
    - name: Show preview report
      ansible.builtin.debug:
        msg: "{{ r }}"

```

Please let us know if the above script still doesn't work.

Thanks,
Dux
