### ISSUE TITLE
Unable to add offline model device to FortiManager 7.4.5 [fmgr_dvm_cmd_add_device] module

### ISSUE THREAD

**Issue by jaimesardina** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#95]
According to FNDN Ansible Documentation, the verified versions goes up to 7.4.2 and I am running 7.4.5 FortiManager so Im here to report a potential issue. I am unable to add a device using blueprint. If its a syntax issue on my end, I apologize. When the playbook is ran, FortiManager creates the task but shows the device fails to initialize database. I verified the sn is valid by manually adding device to FMG.  

```
  tasks:
    - name: Add a model device to FortiManager
      fmgr_dvm_cmd_add_device:
        dvm_cmd_add_device:
          adom: "root"
          flags:
            - "create_task"
            - "nonblocking"
          device:
            name: "{{ device_name }}"
            sn: "{{ device_serial }}"
            device_blueprint: "{{ device_blueprint }}"
            device_action: "add_model"
        access_token: "{{ access_token }}"
      register: add_device_result

```

**Comment by MaxxLiu22** [comment]
Hi @jaimesardina ,

Thank you for bringing up this issue. After monitoring the GUI traffic, I found that we may need to include additional information for FGT in order to successfully add the device. This revised script worked for me and successfully added the device on FMG. Please let me know if this does not resolve your question.
```
  tasks:
    - name: Add a model device to FortiManager
      fmgr_dvm_cmd_add_device:
        dvm_cmd_add_device:
          adom: "root"
          flags:
            - "create_task"
            - "nonblocking"
          device:
            name: "fgt_asb"
            sn: "FGVMULTM24003276"
            device_blueprint: "blueprint"
            device_action: "add_model"
            os_ver: "7.0"
            os_type: "fos"
            mr: "4"
            mgmt_mode: "fmg"
```
![image](https://github.com/user-attachments/assets/d22af585-1189-4781-a59f-e7ce9cda8c73)

Thanks,
Maxx
