### ISSUE TITLE
Add list to fmgr_pkg_firewall_localinpolicy interface option

### ISSUE THREAD

**Issue by cr0cdev** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#96]
Hi!

Please add an option to list all incoming interfaces in `fmgr_pkg_firewall_localinpolicy`. At this moment it is supported as `str` and single object I guess.
Example that works:
```
# Configure local-in policy
- name: Configure user defined IPv4 local-in policies.
  fortinet.fortimanager.fmgr_pkg_firewall_localinpolicy:
    workspace_locking_adom: "{{ adom_name | lower }}"
    bypass_validation: true
    adom: "{{ adom_name | lower }}"
    pkg: "{{ item.policy_pkgname }}"
    state: present
    pkg_firewall_localinpolicy:
      action: "{{ item.policy_action }}"
      dstaddr: "{{ item.policy_dstaddr }}"
      intf: "{{ item.policy_intf }}"
      policyid: "{{ item.policy_id }}"
      schedule: "{{ item.policy_schedule }}"
      service: "{{ item.policy_service }}"
      srcaddr: "{{ item.policy_srcaddr }}"
      status: "{{ item.policy_status }}"
      comments: "{{ item.policy_comment }}"
  loop: "{{ local_policies }}"

local_policies:
  - policy_id: 1
    policy_pkgname: "{{ fw_policy }}"
    policy_action: accept
    policy_comment: Management
    policy_dstaddr: all
    policy_intf: ["wan", "wan1", "wan2"]
    policy_schedule: always
    policy_service:
      - MGMT-SERVICES
    policy_srcaddr:
      - MGMT-SUBNETS
    policy_status: enable
```

This will add `wan`, `wan1`, `wan2` as incoming interfaces.
