### ISSUE TITLE
ha_hbdev is of wrong datatype in fortinet.fortimanager.fmgr_fmg_device_blueprint module

### ISSUE THREAD

**Issue by bhuddah** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#99]
Datatype is "string" instead of "list"

**Comment by dux-fortinet** [comment]
Hi @bhuddah,

Currently, `"ha_hbdev"` datatype is "string" in `fortinet.fortimanager.fmgr_fmg_device_blueprint`. And I checked this parameter in both [FNDN API document](https://fndn.fortinet.net/index.php?/fortiapi/5-fortimanager/4838/5/pm/config/fmg/) and a running FortiManager server, both of them show this `ha_hbdev` is a string parameter. 

The following script works well in my testing:
```
- name: Github99
  hosts: fortimanagers
  vars:
    adom_name: "root"
  tasks:
    - name: Fmg device blueprint
      fortinet.fortimanager.fmgr_fmg_device_blueprint:
        adom: "{{adom_name}}"
        state: present
        fmg_device_blueprint:
          name: test_github99
          ha_hbdev: "test2"
```

Please correct me if I'm wrong. Thanks.

Regards,
Xinwei

**Comment by bhuddah** [comment]
hi,

thanks for the quick follow up.
your evaluation is indeed correct, when you stick with a single HB device.
when you add two or more, it becomes a list, alternating device name and device weight:
`[ "ha1", "50", "ha2", "50"]`
when changing the variable type to list, I can successfully add this.

kindly,
Michael

**Comment by dux-fortinet** [comment]
Hi Michael,

For the current FortiManager Ansible version, you can use "bypass_validation: true" to skip the Ansible parameter validation and set `ha_hbdev` as a list.
```
- name: Github99
  hosts: fortimanagers
  vars:
    adom_name: "root"
  tasks:
    - name: Fmg device blueprint
      fortinet.fortimanager.fmgr_fmg_device_blueprint:
        bypass_validation: true # <--- here
        adom: "{{adom_name}}"
        state: present
        fmg_device_blueprint:
          name: test_github99
          # ha_hbdev: "test2"
          ha_hbdev: ["test1", "test2"]
```

In the next version of FortiManager Ansible, I will change the type of `ha_hbdev` from `string` to `raw`, so you can specify this parameter either as `string` or `list` at that time.
Thanks for pointing it out.

Regards,
Xinwei
